export class FiscalRealIacResourceCatalog {
  public static getCatalog() {
    return [
      {
        resourceId: 'network-segment-dedicated-homologation',
        planned: true,
        iacDefined: true,
        realResourceCreated: false,
        terraformApplied: false,
        pulumiApplied: false,
        cloudFormationDeployed: false,
        activeNow: false,
        endpointCalled: false,
        credentialLoaded: false,
        workerCreated: false,
        productionTrafficAttached: false,
        trafficChanged: false
      },
      {
        resourceId: 'subnet-private-homologation',
        planned: true,
        iacDefined: true,
        realResourceCreated: false,
        terraformApplied: false,
        pulumiApplied: false,
        cloudFormationDeployed: false,
        activeNow: false,
        endpointCalled: false,
        credentialLoaded: false,
        workerCreated: false,
        productionTrafficAttached: false,
        trafficChanged: false
      },
      {
        resourceId: 'security-group-sefaz-egress',
        planned: true,
        iacDefined: true,
        realResourceCreated: false,
        terraformApplied: false,
        pulumiApplied: false,
        cloudFormationDeployed: false,
        activeNow: false,
        endpointCalled: false,
        credentialLoaded: false,
        workerCreated: false,
        productionTrafficAttached: false,
        trafficChanged: false
      },
      {
        resourceId: 'postgres-dedicated-homologation',
        planned: true,
        iacDefined: true,
        realResourceCreated: false,
        terraformApplied: false,
        pulumiApplied: false,
        cloudFormationDeployed: false,
        activeNow: false,
        endpointCalled: false,
        credentialLoaded: false,
        workerCreated: false,
        productionTrafficAttached: false,
        trafficChanged: false
      },
      {
        resourceId: 'secret-vault-dedicated-homologation',
        planned: true,
        iacDefined: true,
        realResourceCreated: false,
        terraformApplied: false,
        pulumiApplied: false,
        cloudFormationDeployed: false,
        activeNow: false,
        endpointCalled: false,
        credentialLoaded: false,
        workerCreated: false,
        productionTrafficAttached: false,
        trafficChanged: false
      },
      {
        resourceId: 'certificate-a1-secret-slot',
        planned: true,
        iacDefined: true,
        realResourceCreated: false,
        terraformApplied: false,
        pulumiApplied: false,
        cloudFormationDeployed: false,
        activeNow: false,
        endpointCalled: false,
        credentialLoaded: false,
        workerCreated: false,
        productionTrafficAttached: false,
        trafficChanged: false
      },
      {
        resourceId: 'xml-signer-service-slot',
        planned: true,
        iacDefined: true,
        realResourceCreated: false,
        terraformApplied: false,
        pulumiApplied: false,
        cloudFormationDeployed: false,
        activeNow: false,
        endpointCalled: false,
        credentialLoaded: false,
        workerCreated: false,
        productionTrafficAttached: false,
        trafficChanged: false
      },
      {
        resourceId: 'danfe-renderer-service-slot',
        planned: true,
        iacDefined: true,
        realResourceCreated: false,
        terraformApplied: false,
        pulumiApplied: false,
        cloudFormationDeployed: false,
        activeNow: false,
        endpointCalled: false,
        credentialLoaded: false,
        workerCreated: false,
        productionTrafficAttached: false,
        trafficChanged: false
      },
      {
        resourceId: 'observability-log-sink',
        planned: true,
        iacDefined: true,
        realResourceCreated: false,
        terraformApplied: false,
        pulumiApplied: false,
        cloudFormationDeployed: false,
        activeNow: false,
        endpointCalled: false,
        credentialLoaded: false,
        workerCreated: false,
        productionTrafficAttached: false,
        trafficChanged: false
      },
      {
        resourceId: 'observability-metric-sink',
        planned: true,
        iacDefined: true,
        realResourceCreated: false,
        terraformApplied: false,
        pulumiApplied: false,
        cloudFormationDeployed: false,
        activeNow: false,
        endpointCalled: false,
        credentialLoaded: false,
        workerCreated: false,
        productionTrafficAttached: false,
        trafficChanged: false
      },
      {
        resourceId: 'rollback-control-plane-slot',
        planned: true,
        iacDefined: true,
        realResourceCreated: false,
        terraformApplied: false,
        pulumiApplied: false,
        cloudFormationDeployed: false,
        activeNow: false,
        endpointCalled: false,
        credentialLoaded: false,
        workerCreated: false,
        productionTrafficAttached: false,
        trafficChanged: false
      },
      {
        resourceId: 'circuit-breaker-config-slot',
        planned: true,
        iacDefined: true,
        realResourceCreated: false,
        terraformApplied: false,
        pulumiApplied: false,
        cloudFormationDeployed: false,
        activeNow: false,
        endpointCalled: false,
        credentialLoaded: false,
        workerCreated: false,
        productionTrafficAttached: false,
        trafficChanged: false
      },
      {
        resourceId: 'kill-switch-config-slot',
        planned: true,
        iacDefined: true,
        realResourceCreated: false,
        terraformApplied: false,
        pulumiApplied: false,
        cloudFormationDeployed: false,
        activeNow: false,
        endpointCalled: false,
        credentialLoaded: false,
        workerCreated: false,
        productionTrafficAttached: false,
        trafficChanged: false
      },
      {
        resourceId: 'rate-limit-gateway-slot',
        planned: true,
        iacDefined: true,
        realResourceCreated: false,
        terraformApplied: false,
        pulumiApplied: false,
        cloudFormationDeployed: false,
        activeNow: false,
        endpointCalled: false,
        credentialLoaded: false,
        workerCreated: false,
        productionTrafficAttached: false,
        trafficChanged: false
      }
    ];
  }
}
