import { FiscalRealCommandManifestItem } from './FiscalRealCommandManifestTypes';

export class FiscalRealCommandManifestCatalog {
  public static getCatalog(): FiscalRealCommandManifestItem[] {
    return [
      {
        id: 'CM-01',
        domain: 'IAC_COMMANDS',
        label: 'PREVIEW_IAC_PLAN_INTENT',
        commandIntent: 'View IaC Plan',
        commandPreview: 'terraform plan -detailed-exitcode',
        realCommandIncluded: false,
        executableCommandIncluded: false,
        shellCommandIncluded: false,
        containsSecret: false,
        containsPayload: false,
        executionAllowed: false,
        requiresNewExplicitModule: true,
        blockerReason: 'Command intent only, not a shell script'
      },
      {
        id: 'CM-02',
        domain: 'IAC_COMMANDS',
        label: 'PREVIEW_TERRAFORM_APPLY_INTENT',
        commandIntent: 'Apply Terraform',
        commandPreview: '<intent: terraform apply>',
        realCommandIncluded: false,
        executableCommandIncluded: false,
        shellCommandIncluded: false,
        containsSecret: false,
        containsPayload: false,
        executionAllowed: false,
        requiresNewExplicitModule: true,
        blockerReason: 'Explicitly stripped terraform apply command'
      },
      {
        id: 'CM-03',
        domain: 'IAC_COMMANDS',
        label: 'PREVIEW_PULUMI_UP_INTENT',
        commandIntent: 'Apply Pulumi',
        commandPreview: '<intent: pulumi up>',
        realCommandIncluded: false,
        executableCommandIncluded: false,
        shellCommandIncluded: false,
        containsSecret: false,
        containsPayload: false,
        executionAllowed: false,
        requiresNewExplicitModule: true,
        blockerReason: 'Explicitly stripped pulumi up command'
      },
      {
        id: 'CM-04',
        domain: 'INFRASTRUCTURE',
        label: 'PREVIEW_CLOUD_DEPLOY_INTENT',
        commandIntent: 'Cloud Resource Deployment',
        commandPreview: '<intent: cloud deploy>',
        realCommandIncluded: false,
        executableCommandIncluded: false,
        shellCommandIncluded: false,
        containsSecret: false,
        containsPayload: false,
        executionAllowed: false,
        requiresNewExplicitModule: true,
        blockerReason: 'Cloud deploy commands blocked'
      },
      {
        id: 'CM-05',
        domain: 'DATABASE',
        label: 'PREVIEW_DATABASE_PROVISIONING_INTENT',
        commandIntent: 'Database Provisioning',
        commandPreview: '<intent: db provision>',
        realCommandIncluded: false,
        executableCommandIncluded: false,
        shellCommandIncluded: false,
        containsSecret: false,
        containsPayload: false,
        executionAllowed: false,
        requiresNewExplicitModule: true,
        blockerReason: 'Database provisioning blocked'
      },
      {
        id: 'CM-06',
        domain: 'SECRET_VAULT',
        label: 'PREVIEW_VAULT_PROVISIONING_INTENT',
        commandIntent: 'Vault Provisioning',
        commandPreview: '<intent: vault provision>',
        realCommandIncluded: false,
        executableCommandIncluded: false,
        shellCommandIncluded: false,
        containsSecret: false,
        containsPayload: false,
        executionAllowed: false,
        requiresNewExplicitModule: true,
        blockerReason: 'Vault provisioning blocked'
      },
      {
        id: 'CM-07',
        domain: 'SECRET_VAULT',
        label: 'PREVIEW_SECRET_WRITE_INTENT',
        commandIntent: 'Write Secret to Vault',
        commandPreview: '<intent: write secret>',
        realCommandIncluded: false,
        executableCommandIncluded: false,
        shellCommandIncluded: false,
        containsSecret: false,
        containsPayload: false,
        executionAllowed: false,
        requiresNewExplicitModule: true,
        blockerReason: 'Secret modification blocked'
      },
      {
        id: 'CM-08',
        domain: 'CERTIFICATE',
        label: 'PREVIEW_CERTIFICATE_LOAD_INTENT',
        commandIntent: 'Load A1 Certificate',
        commandPreview: '<intent: load certificate>',
        realCommandIncluded: false,
        executableCommandIncluded: false,
        shellCommandIncluded: false,
        containsSecret: false,
        containsPayload: false,
        executionAllowed: false,
        requiresNewExplicitModule: true,
        blockerReason: 'Certificate parsing blocked'
      },
      {
        id: 'CM-09',
        domain: 'SEFAZ',
        label: 'PREVIEW_SEFAZ_HOMOLOGATION_INTENT',
        commandIntent: 'Sefaz Integration',
        commandPreview: '<intent: call sefaz>',
        realCommandIncluded: false,
        executableCommandIncluded: false,
        shellCommandIncluded: false,
        containsSecret: false,
        containsPayload: false,
        executionAllowed: false,
        requiresNewExplicitModule: true,
        blockerReason: 'Sefaz endpoints blocked'
      },
      {
        id: 'CM-10',
        domain: 'XML_SIGNER',
        label: 'PREVIEW_XML_SIGNING_INTENT',
        commandIntent: 'Sign XML Invoice',
        commandPreview: '<intent: sign xml>',
        realCommandIncluded: false,
        executableCommandIncluded: false,
        shellCommandIncluded: false,
        containsSecret: false,
        containsPayload: false,
        executionAllowed: false,
        requiresNewExplicitModule: true,
        blockerReason: 'Signer disabled'
      },
      {
        id: 'CM-11',
        domain: 'DANFE',
        label: 'PREVIEW_PDF_GENERATION_INTENT',
        commandIntent: 'Generate Invoice PDF',
        commandPreview: '<intent: generate pdf>',
        realCommandIncluded: false,
        executableCommandIncluded: false,
        shellCommandIncluded: false,
        containsSecret: false,
        containsPayload: false,
        executionAllowed: false,
        requiresNewExplicitModule: true,
        blockerReason: 'Renderer disabled'
      },
      {
        id: 'CM-12',
        domain: 'PRODUCTION_V2',
        label: 'PREVIEW_PRODUCTION_V2_INTENT',
        commandIntent: 'Activate Traffic',
        commandPreview: '<intent: traffic shift>',
        realCommandIncluded: false,
        executableCommandIncluded: false,
        shellCommandIncluded: false,
        containsSecret: false,
        containsPayload: false,
        executionAllowed: false,
        requiresNewExplicitModule: true,
        blockerReason: 'V2 flags securely locked'
      }
    ];
  }
}
