import {
  FiscalProductionPostGoLiveRemediationInput,
  FiscalProductionPostGoLiveRemediationResult,
  FiscalProductionPostGoLiveRemediationStatus
} from './FiscalProductionPostGoLiveRemediationTypes';
import { FiscalProductionPostGoLiveRemediationValidator } from './FiscalProductionPostGoLiveRemediationValidator';
import { FiscalProductionPostGoLiveRemediationEvaluationService } from './FiscalProductionPostGoLiveRemediationEvaluationService';

export class FiscalProductionPostGoLiveRemediationDecisionService {
  public static simulateDecision(input: FiscalProductionPostGoLiveRemediationInput): FiscalProductionPostGoLiveRemediationResult {
    const errors = FiscalProductionPostGoLiveRemediationValidator.validate(input);
    const warnings = FiscalProductionPostGoLiveRemediationEvaluationService.evaluate(input);

    const isBlocked = errors.length > 0;

    return {
      success: !isBlocked,
      status: isBlocked ? FiscalProductionPostGoLiveRemediationStatus.BLOCKED_FOR_REAL_WAR_ROOM_OR_REMEDIATION : FiscalProductionPostGoLiveRemediationStatus.PRODUCTION_POST_GO_LIVE_WAR_ROOM_DRILL_READY,
      validationExecuted: true,
      evaluationExecuted: true,
      decisionSimulated: true,
      warRoomDrillNoActivationBlueprintGenerated: true,
      remediationReadinessNoExecutePlanGenerated: true,
      mitigationPlaybookNoOpMatrixGenerated: true,
      supportHandoverNoConclusionPlanGenerated: true,
      supportRoleNoGrantMatrixGenerated: true,
      assistedSessionNoOpenPlanGenerated: true,
      stabilizationDecisionNoAuthorizationMatrixGenerated: true,
      warRoomCommunicationNoSendPlanGenerated: true,
      postGoLiveRemediationNoPersistencePlanGenerated: true,
      noRealWarRoomEvidenceGenerated: true,
      noRealRemediationEvidenceGenerated: true,
      dependencyMatrixGenerated: true,
      blockersGenerated: true,
      risksGenerated: true,
      go: false,
      noGo: true,
      blockers: errors,
      warnings,
      productionPostGoLiveRemediationDryRunOnly: true,
      warRoomDrillNoActivationOnly: true,
      remediationReadinessNoExecuteOnly: true,
      supportHandoverNoConclusionOnly: true,
      realWarRoomActivated: false,
      realCrisisRoomCreated: false,
      realIncidentOpened: false,
      realTicketCreated: false,
      realRemediationExecuted: false,
      realMitigationExecuted: false,
      realRunbookExecuted: false,
      realSupportAccessGranted: false,
      realRbacChanged: false,
      realAssistedSessionOpened: false,
      realSupportHandoverConcluded: false,
      realStabilizationDecisionAuthorized: false,
      realOperatorNotified: false,
      realSreNotified: false,
      realCustomerNotified: false,
      realStakeholderNotified: false,
      realApproverNotified: false,
      webhookSent: false,
      slackSent: false,
      whatsappSent: false,
      emailSent: false,
      pagerSent: false,
      pagerDutySent: false,
      opsgenieSent: false,
      realAlertCreated: false,
      realObservabilityInstalled: false,
      realMetricsCaptured: false,
      realLogsCaptured: false,
      realTracesCaptured: false,
      realTelemetryRead: false,
      realGoLiveConcluded: false,
      realCutoverExecuted: false,
      productionV2Activated: false,
      routeToV2: false,
      routeToLegacy: true,
      trafficChanged: false,
      realLoadBalancerSwitched: false,
      realDnsChanged: false,
      realProxyInstalled: false,
      realMiddlewareInstalled: false,
      realTapInstalled: false,
      realShadowTrafficEnabled: false,
      realRequestCaptured: false,
      realResponseCaptured: false,
      realPayloadCaptured: false,
      realLegacyHandlerCalled: false,
      realV2HandlerCalled: false,
      realExecutionGateUnlocked: false,
      realAuthorizationGranted: false,
      realAuthorizationTokenIssued: false,
      realRollbackExecuted: false,
      realAbortExecuted: false,
      realFallbackExecuted: false,
      realReleaseExecuted: false,
      realRolloutExecuted: false,
      realCanaryActivated: false,
      realShutdownExecuted: false,
      realRuntimeStarted: false,
      realQueueStarted: false,
      realJobEnqueued: false,
      realWorkerDispatched: false,
      realShellCommandExecuted: false,
      realDatabaseConnected: false,
      dmlExecuted: false,
      ddlExecuted: false,
      realSefazCalled: false,
      realPayloadRead: false,
      realXmlRead: false,
      realPdfRead: false,
      realPfxRead: false,
      realCertificateRead: false,
      certificatePasswordRead: false,
      realSecretRead: false,
      privateKeyRead: false,
      tokenRead: false,
      realCryptoUsed: false,
      realHashCalculated: false,
      xmlSigned: false,
      pdfGenerated: false,
      fileSystemWritten: false,
      externalStorageUploaded: false,
      readOnly: true,
      governanceOnly: true,
      simulationOnly: true,
      activationBlocked: true,
      payloadIncluded: false,
      sensitiveDataIncluded: false,
      approvedForWarRoomDocumentation: true,
      approvedForRemediationReadinessReview: true,
      approvedForSupportHandoverSimulation: true,
      approvedForRealWarRoomActivation: false,
      approvedForRealRemediationExecution: false,
      approvedForProductionV2: false,
      approvedForRouteToV2: false
    };
  }
}
