import {
  FiscalProductionPostGoLiveIncidentReadinessInput,
  FiscalProductionPostGoLiveIncidentReadinessResult,
  FiscalProductionPostGoLiveIncidentReadinessStatus
} from './FiscalProductionPostGoLiveIncidentReadinessTypes';
import { FiscalProductionPostGoLiveIncidentReadinessValidator } from './FiscalProductionPostGoLiveIncidentReadinessValidator';
import { FiscalProductionPostGoLiveIncidentReadinessEvaluationService } from './FiscalProductionPostGoLiveIncidentReadinessEvaluationService';

export class FiscalProductionPostGoLiveIncidentReadinessDecisionService {
  public static simulateDecision(input: FiscalProductionPostGoLiveIncidentReadinessInput): FiscalProductionPostGoLiveIncidentReadinessResult {
    const errors = FiscalProductionPostGoLiveIncidentReadinessValidator.validate(input);
    const warnings = FiscalProductionPostGoLiveIncidentReadinessEvaluationService.evaluate(input);

    const isBlocked = errors.length > 0;

    return {
      success: !isBlocked,
      status: isBlocked ? FiscalProductionPostGoLiveIncidentReadinessStatus.BLOCKED_FOR_REAL_INCIDENT_OR_RUNBOOK_EXECUTION : FiscalProductionPostGoLiveIncidentReadinessStatus.PRODUCTION_POST_GO_LIVE_INCIDENT_READINESS_BLUEPRINT_READY,
      validationExecuted: true,
      evaluationExecuted: true,
      decisionSimulated: true,
      incidentReadinessBlueprintGenerated: true,
      incidentTriageNoOpenMatrixGenerated: true,
      incidentSeveritySimulationMatrixGenerated: true,
      supportRunbookNoExecutePlanGenerated: true,
      mitigationActionNoOpCatalogGenerated: true,
      escalationNoNotificationPlanGenerated: true,
      incidentCommunicationNoSendPlanGenerated: true,
      postIncidentReviewNoPersistencePlanGenerated: true,
      incidentEvidenceNoCaptureMatrixGenerated: true,
      noRealIncidentEvidenceGenerated: true,
      noRealRunbookExecutionEvidenceGenerated: true,
      dependencyMatrixGenerated: true,
      blockersGenerated: true,
      risksGenerated: true,
      go: false,
      noGo: true,
      blockers: errors,
      warnings,
      productionPostGoLiveIncidentReadinessDryRunOnly: true,
      incidentTriageNoOpenOnly: true,
      supportRunbookNoExecuteOnly: true,
      realIncidentOpened: false,
      realTicketCreated: false,
      realRunbookExecuted: false,
      realMitigationExecuted: false,
      realRemediationExecuted: false,
      realOperatorNotified: false,
      realSreNotified: false,
      realCustomerNotified: false,
      realStakeholderNotified: false,
      realApproverNotified: false,
      webhookSent: false,
      slackSent: false,
      whatsappSent: false,
      emailSent: false,
      pagerSent: false,
      pagerDutySent: false,
      opsgenieSent: false,
      realAlertCreated: false,
      realObservabilityInstalled: false,
      realMetricsCaptured: false,
      realLogsCaptured: false,
      realTracesCaptured: false,
      realProductionObserved: false,
      realGoLiveConcluded: false,
      realCutoverExecuted: false,
      productionV2Activated: false,
      routeToV2: false,
      routeToLegacy: true,
      trafficChanged: false,
      realLoadBalancerSwitched: false,
      realDnsChanged: false,
      realProxyInstalled: false,
      realMiddlewareInstalled: false,
      realTapInstalled: false,
      realShadowTrafficEnabled: false,
      realRequestCaptured: false,
      realResponseCaptured: false,
      realPayloadCaptured: false,
      realLegacyHandlerCalled: false,
      realV2HandlerCalled: false,
      realExecutionGateUnlocked: false,
      realAuthorizationGranted: false,
      realAuthorizationTokenIssued: false,
      realRollbackExecuted: false,
      realAbortExecuted: false,
      realFallbackExecuted: false,
      realReleaseExecuted: false,
      realRolloutExecuted: false,
      realCanaryActivated: false,
      realShutdownExecuted: false,
      realRuntimeStarted: false,
      realQueueStarted: false,
      realJobEnqueued: false,
      realWorkerDispatched: false,
      realShellCommandExecuted: false,
      realDatabaseConnected: false,
      dmlExecuted: false,
      ddlExecuted: false,
      realSefazCalled: false,
      realPayloadRead: false,
      realXmlRead: false,
      realPdfRead: false,
      realPfxRead: false,
      realCertificateRead: false,
      certificatePasswordRead: false,
      realSecretRead: false,
      privateKeyRead: false,
      tokenRead: false,
      realCryptoUsed: false,
      realHashCalculated: false,
      xmlSigned: false,
      pdfGenerated: false,
      fileSystemWritten: false,
      externalStorageUploaded: false,
      readOnly: true,
      governanceOnly: true,
      simulationOnly: true,
      activationBlocked: true,
      payloadIncluded: false,
      sensitiveDataIncluded: false,
      approvedForIncidentReadinessDocumentation: true,
      approvedForTriageSimulation: true,
      approvedForRunbookNoOpReview: true,
      approvedForRealIncidentOpen: false,
      approvedForRealRunbookExecution: false,
      approvedForProductionV2: false,
      approvedForRouteToV2: false
    };
  }
}
