import {
  FiscalProductionComplianceAuditClosureInput,
  FiscalProductionComplianceAuditClosureResult,
  FiscalProductionComplianceAuditClosureStatus
} from './FiscalProductionComplianceAuditClosureTypes';
import { FiscalProductionComplianceAuditClosureValidator } from './FiscalProductionComplianceAuditClosureValidator';
import { FiscalProductionComplianceAuditClosureEvaluationService } from './FiscalProductionComplianceAuditClosureEvaluationService';

export class FiscalProductionComplianceAuditClosureDecisionService {
  public static simulateDecision(input: FiscalProductionComplianceAuditClosureInput): FiscalProductionComplianceAuditClosureResult {
    const errors = FiscalProductionComplianceAuditClosureValidator.validate(input);
    const warnings = FiscalProductionComplianceAuditClosureEvaluationService.evaluate(input);

    const isBlocked = errors.length > 0;

    return {
      success: !isBlocked,
      status: isBlocked ? FiscalProductionComplianceAuditClosureStatus.BLOCKED_FOR_REAL_COMPLIANCE_AUDIT_CLOSURE : FiscalProductionComplianceAuditClosureStatus.PRODUCTION_COMPLIANCE_AUDIT_GOVERNANCE_CLOSURE_READY,
      validationExecuted: true,
      evaluationExecuted: true,
      decisionSimulated: true,
      closureInventoryGenerated: true,
      finalChecklistGenerated: true,
      evidencePackageGenerated: true,
      noSubmissionHandoffGenerated: true,
      postClosureRoadmapGenerated: true,
      finalBlockersGenerated: true,
      finalRisksGenerated: true,
      go: false,
      noGo: true, // as specified: go: false, noGo: true
      blockers: errors,
      warnings,
      productionComplianceAuditGovernanceClosureOnly: true,
      finalNoSubmissionEvidenceOnly: true,
      noSubmissionHandoffOnly: true,
      realClosureExecuted: false,
      realRegulatoryFilingSubmitted: false,
      realAuditorPackageSent: false,
      realAuditDossierCreated: false,
      realProtocolNumberGenerated: false,
      realFindingCreated: false,
      realRemediationExecuted: false,
      realReleaseApproved: false,
      realRollbackExecuted: false,
      realV2ShutdownExecuted: false,
      realKillSwitchActivated: false,
      trafficChanged: false,
      routeToV2: false,
      routeToLegacy: true,
      realExecutionGateUnlocked: false,
      realAuthorizationGranted: false,
      realAuthorizationTokenIssued: false,
      realPayloadRead: false,
      realXmlRead: false,
      realPdfRead: false,
      realPfxRead: false,
      realCertificateRead: false,
      certificatePasswordRead: false,
      realSecretRead: false,
      privateKeyRead: false,
      tokenRead: false,
      realCryptoUsed: false,
      realHashCalculated: false,
      xmlSigned: false,
      pdfGenerated: false,
      fileSystemWritten: false,
      databaseWritten: false,
      externalStorageUploaded: false,
      realDatabaseConnected: false,
      dmlExecuted: false,
      ddlExecuted: false,
      realSefazCalled: false,
      webhookSent: false,
      slackSent: false,
      whatsappSent: false,
      emailSent: false,
      pagerSent: false,
      pagerDutySent: false,
      opsgenieSent: false,
      realAuditorNotified: false,
      realRegulatorNotified: false,
      realStakeholderNotified: false,
      realApproverNotified: false,
      realCustomerNotified: false,
      productionV2Activated: false,
      readOnly: true,
      governanceOnly: true,
      simulationOnly: true,
      activationBlocked: true,
      payloadIncluded: false,
      sensitiveDataIncluded: false,
      approvedForComplianceAuditClosure: true,
      approvedForFinalNoSubmissionEvidence: true,
      approvedForNoSubmissionHandoff: true,
      approvedForRealRegulatorySubmission: false,
      approvedForRealAuditPackage: false,
      approvedForRealReleaseApproval: false,
      approvedForRealRollback: false,
      approvedForRealV2Shutdown: false,
      approvedForProductionV2: false,
      approvedForRouteToV2: false
    };
  }
}
