import {
  FiscalProductionCorporateBoardReviewInput,
  FiscalProductionCorporateBoardReviewResult,
  FiscalProductionCorporateBoardReviewStatus
} from './FiscalProductionCorporateBoardReviewTypes';
import { FiscalProductionCorporateBoardReviewValidator } from './FiscalProductionCorporateBoardReviewValidator';
import { FiscalProductionCorporateBoardReviewEvaluationService } from './FiscalProductionCorporateBoardReviewEvaluationService';

export class FiscalProductionCorporateBoardReviewDecisionService {
  public static simulateDecision(input: FiscalProductionCorporateBoardReviewInput): FiscalProductionCorporateBoardReviewResult {
    const errors = FiscalProductionCorporateBoardReviewValidator.validate(input);
    const warnings = FiscalProductionCorporateBoardReviewEvaluationService.evaluate(input);
    const isBlocked = errors.length > 0;

    return {
      success: !isBlocked,
      status: isBlocked ? FiscalProductionCorporateBoardReviewStatus.BLOCKED_FOR_REAL_BOARD_APPROVAL_OR_NOTIFICATION : FiscalProductionCorporateBoardReviewStatus.PRODUCTION_CORPORATE_BOARD_REVIEW_BLUEPRINT_READY,
      validationExecuted: true,
      evaluationExecuted: true,
      decisionSimulated: true,
      boardReviewBlueprintGenerated: true,
      executiveAcknowledgementNonBindingMatrixGenerated: true,
      boardQuorumSimulationMatrixGenerated: true,
      boardMemberEligibilityNoAuthorityMatrixGenerated: true,
      archiveReviewNoReadMatrixGenerated: true,
      boardDecisionNoApprovalMatrixGenerated: true,
      boardMinutesNoFilePlanGenerated: true,
      executiveAcknowledgementNoPersistencePlanGenerated: true,
      boardNotificationNoSendPlanGenerated: true,
      boardNoLegalEffectNoticeGenerated: true,
      noRealBoardApprovalEvidenceGenerated: true,
      noRealAcknowledgementEvidenceGenerated: true,
      noRealBoardNotificationEvidenceGenerated: true,
      dependencyMatrixGenerated: true,
      blockersGenerated: true,
      risksGenerated: true,
      go: false,
      noGo: true,
      blockers: errors,
      warnings,
      productionCorporateBoardReviewOnly: true,
      executiveAcknowledgementNonBindingOnly: true,
      noRealBoardApprovalOnly: true,
      noRealAcknowledgementOnly: true,
      noRealNotificationOnly: true,
      noRealRecordOnly: true,
      noRealFileOnly: true,
      noPersistenceOnly: true,
      noExportOnly: true,
      noLegalEffectOnly: true,
      noPayloadReadOnly: true,
      noDatabaseReadOnly: true,
      noExternalSubmissionOnly: true,
      realBoardReviewConcluded: false,
      realExecutiveAcknowledgementCollected: false,
      realBoardApprovalCreated: false,
      realBoardMinutesCreated: false,
      realMeetingRecordGenerated: false,
      realPdfGenerated: false,
      realZipGenerated: false,
      realJsonGenerated: false,
      realCsvGenerated: false,
      realBoardRecordPersisted: false,
      realAcknowledgementRecordPersisted: false,
      realBoardPackageExported: false,
      realBoardPackageSent: false,
      realStakeholderNotified: false,
      realDirectorNotified: false,
      realAuditorNotified: false,
      realRegulatorNotified: false,
      realHashGenerated: false,
      realSignatureGenerated: false,
      realProofCreated: false,
      realCryptographicProofCreated: false,
      realPayloadRead: false,
      realXmlRead: false,
      realPdfRead: false,
      realTenantDataRead: false,
      realFiscalDocumentRead: false,
      realFilesystemWritten: false,
      realStorageUploaded: false,
      realDatabaseWritten: false,
      realGoLiveApproved: false,
      realGoLiveExecuted: false,
      realActivationCommandExecuted: false,
      realActivationAuthorityGranted: false,
      realExecutionGateUnlocked: false,
      realAuthorizationTokenIssued: false,
      productionV2Activated: false,
      routeToV2: false,
      routeToLegacy: true,
      realTrafficChanged: false,
      realRuntimeStarted: false,
      realQueueStarted: false,
      realJobEnqueued: false,
      realWorkerDispatched: false,
      realDatabaseConnected: false,
      dmlExecuted: false,
      ddlExecuted: false,
      realMigrationRun: false,
      realSefazCalled: false,
      realExternalApiCalled: false,
      realWebhookSent: false,
      realSlackSent: false,
      realWhatsappSent: false,
      realEmailSent: false,
      realPagerSent: false,
      tokenRead: false,
      realSecretRead: false,
      apiKeyRead: false,
      clientSecretRead: false,
      authorizationHeaderRead: false,
      databaseUrlRead: false,
      connectionStringRead: false,
      realCertificateRead: false,
      realPfxRead: false,
      certificatePasswordRead: false,
      privateKeyRead: false,
      realCryptoUsed: false,
      xmlSigned: false,
      readOnly: true,
      governanceOnly: true,
      simulationOnly: true,
      activationBlocked: true,
      payloadIncluded: false,
      sensitiveDataIncluded: false,
      approvedForVirtualBoardReviewDocumentation: true,
      approvedForNonBindingAcknowledgementDocumentation: true,
      approvedForRealBoardApproval: false,
      approvedForRealAcknowledgementCollection: false,
      approvedForRealNotification: false,
      approvedForRealRecordPersistence: false,
      approvedForRealExport: false,
      approvedForRealGoLiveApproval: false,
      approvedForRealGoLiveExecution: false,
      approvedForProductionV2: false,
      approvedForRouteToV2: false,
      lintGlobalKnownIssueAcknowledged: true,
      ts2308KnownIssueAcknowledged: true,
      namespaceOverlapIntroducedByModule43_2: false
    };
  }
}
