import {
  FiscalProductionTrafficRoutingInput,
  FiscalProductionTrafficRoutingResult,
  FiscalProductionTrafficRoutingStatus
} from './FiscalProductionTrafficRoutingTypes';
import { FiscalProductionTrafficRoutingValidator } from './FiscalProductionTrafficRoutingValidator';
import { FiscalProductionTrafficRoutingEvaluationService } from './FiscalProductionTrafficRoutingEvaluationService';

export class FiscalProductionTrafficRoutingDecisionService {
  public static simulateDecision(input: FiscalProductionTrafficRoutingInput): FiscalProductionTrafficRoutingResult {
    const errors = FiscalProductionTrafficRoutingValidator.validate(input);
    const warnings = FiscalProductionTrafficRoutingEvaluationService.evaluate(input);

    const isBlocked = errors.length > 0;

    return {
      success: !isBlocked,
      status: isBlocked ? FiscalProductionTrafficRoutingStatus.BLOCKED_FOR_REAL_TRAFFIC_ROUTING_OR_LB_SWITCH : FiscalProductionTrafficRoutingStatus.PRODUCTION_TRAFFIC_ROUTING_NO_OP_READY,
      validationExecuted: true,
      evaluationExecuted: true,
      decisionSimulated: true,
      trafficRoutingNoOpBlueprintGenerated: true,
      loadBalancerSwitchNoOpContractGenerated: true,
      routeMappingSimulationMatrixGenerated: true,
      dnsRoutingNoChangePlanGenerated: true,
      proxyMiddlewareTapNoInstallMatrixGenerated: true,
      shadowTrafficNoCapturePlanGenerated: true,
      trafficSliceSimulationMatrixGenerated: true,
      legacyPriorityPreservationPlanGenerated: true,
      noTrafficMutationEvidenceGenerated: true,
      noLoadBalancerSwitchEvidenceGenerated: true,
      dependencyMatrixGenerated: true,
      blockersGenerated: true,
      risksGenerated: true,
      go: false,
      noGo: true,
      blockers: errors,
      warnings,
      productionTrafficRoutingNoOpOnly: true,
      loadBalancerSwitchNoOpOnly: true,
      noTrafficMutationEvidenceOnly: true,
      trafficChanged: false,
      routeToV2: false,
      routeToLegacy: true,
      productionV2Activated: false,
      realCutoverExecuted: false,
      realGoLiveExecuted: false,
      realLoadBalancerSwitched: false,
      realDnsChanged: false,
      realProxyInstalled: false,
      realMiddlewareInstalled: false,
      realTapInstalled: false,
      realShadowTrafficEnabled: false,
      realRequestDuplicated: false,
      realRequestCaptured: false,
      realResponseCaptured: false,
      realPayloadCaptured: false,
      realLegacyHandlerCalled: false,
      realV2HandlerCalled: false,
      realExecutionGateUnlocked: false,
      realAuthorizationGranted: false,
      realAuthorizationTokenIssued: false,
      realDeployExecuted: false,
      realReleaseExecuted: false,
      realRolloutExecuted: false,
      realCanaryActivated: false,
      realRollbackExecuted: false,
      realShutdownExecuted: false,
      realRuntimeStarted: false,
      realQueueStarted: false,
      realJobEnqueued: false,
      realWorkerDispatched: false,
      realShellCommandExecuted: false,
      realDatabaseConnected: false,
      dmlExecuted: false,
      ddlExecuted: false,
      realSefazCalled: false,
      realPayloadRead: false,
      realXmlRead: false,
      realPdfRead: false,
      realPfxRead: false,
      realCertificateRead: false,
      certificatePasswordRead: false,
      realSecretRead: false,
      privateKeyRead: false,
      tokenRead: false,
      realCryptoUsed: false,
      realHashCalculated: false,
      xmlSigned: false,
      pdfGenerated: false,
      fileSystemWritten: false,
      externalStorageUploaded: false,
      webhookSent: false,
      slackSent: false,
      whatsappSent: false,
      emailSent: false,
      pagerSent: false,
      pagerDutySent: false,
      opsgenieSent: false,
      realStakeholderNotified: false,
      realApproverNotified: false,
      realCustomerNotified: false,
      realOperatorNotified: false,
      readOnly: true,
      governanceOnly: true,
      simulationOnly: true,
      activationBlocked: true,
      payloadIncluded: false,
      sensitiveDataIncluded: false,
      approvedForTrafficRoutingNoOp: true,
      approvedForLoadBalancerSwitchNoOp: true,
      approvedForNoTrafficMutationEvidence: true,
      approvedForRealTrafficChange: false,
      approvedForRealLoadBalancerSwitch: false,
      approvedForProductionV2: false,
      approvedForRouteToV2: false
    };
  }
}
