import {
  FiscalProductionComplianceRollbackShutdownInput,
  FiscalProductionComplianceRollbackShutdownResult,
  FiscalProductionComplianceRollbackShutdownStatus
} from './FiscalProductionComplianceRollbackShutdownTypes';
import { FiscalProductionComplianceRollbackShutdownValidator } from './FiscalProductionComplianceRollbackShutdownValidator';
import { FiscalProductionComplianceRollbackShutdownEvaluationService } from './FiscalProductionComplianceRollbackShutdownEvaluationService';

export class FiscalProductionComplianceRollbackShutdownDecisionService {
  public static simulateDecision(input: FiscalProductionComplianceRollbackShutdownInput): FiscalProductionComplianceRollbackShutdownResult {
    const errors = FiscalProductionComplianceRollbackShutdownValidator.validate(input);
    const warnings = FiscalProductionComplianceRollbackShutdownEvaluationService.evaluate(input);

    const isBlocked = errors.length > 0;

    return {
      success: !isBlocked,
      status: isBlocked ? FiscalProductionComplianceRollbackShutdownStatus.BLOCKED_FOR_REAL_ROLLBACK_OR_SHUTDOWN : FiscalProductionComplianceRollbackShutdownStatus.PRODUCTION_COMPLIANCE_ROLLBACK_NO_OP_READY,
      validationExecuted: true,
      evaluationExecuted: true,
      decisionSimulated: true,
      rollbackNoOpBlueprintGenerated: !isBlocked,
      v2ShutdownNoOpContractGenerated: !isBlocked,
      rollbackEligibilitySimulationMatrixGenerated: !isBlocked,
      v2ShutdownTriggerNoExecuteMatrixGenerated: !isBlocked,
      legacyContinuityDuringRollbackPlanGenerated: !isBlocked,
      trafficReversionNoOpPlanGenerated: !isBlocked,
      regulatoryRollbackEvidenceSimulationMatrixGenerated: !isBlocked,
      postRollbackComplianceReviewNoPersistencePlanGenerated: !isBlocked,
      noRealRollbackEvidenceGenerated: !isBlocked,
      noRealV2ShutdownEvidenceGenerated: !isBlocked,
      dependencyMatrixGenerated: !isBlocked,
      blockersGenerated: true,
      risksGenerated: true,
      go: !isBlocked,
      noGo: isBlocked,
      blockers: errors,
      warnings,
      productionComplianceRollbackNoOpOnly: true,
      productionV2ShutdownNoOpOnly: true,
      noRealRollbackEvidenceOnly: true,
      realRollbackExecuted: false,
      realV2ShutdownExecuted: false,
      realKillSwitchActivated: false,
      realTrafficReverted: false,
      trafficChanged: false,
      routeToV2: false,
      routeToLegacy: true,
      realReleaseApproved: false,
      realExecutionGateUnlocked: false,
      realAuthorizationGranted: false,
      realAuthorizationTokenIssued: false,
      realIncidentCreated: false,
      realTicketCreated: false,
      realRemediationExecuted: false,
      realRegulatoryFilingSubmitted: false,
      realProtocolNumberGenerated: false,
      realRollbackRecordPersisted: false,
      realShutdownRecordPersisted: false,
      realAuditRecordPersisted: false,
      realPayloadRead: false,
      realXmlRead: false,
      realPdfRead: false,
      realPfxRead: false,
      realCertificateRead: false,
      certificatePasswordRead: false,
      realSecretRead: false,
      privateKeyRead: false,
      tokenRead: false,
      realCryptoUsed: false,
      realHashCalculated: false,
      xmlSigned: false,
      pdfGenerated: false,
      fileSystemWritten: false,
      databaseWritten: false,
      externalStorageUploaded: false,
      realDatabaseConnected: false,
      dmlExecuted: false,
      ddlExecuted: false,
      realSefazCalled: false,
      webhookSent: false,
      slackSent: false,
      whatsappSent: false,
      emailSent: false,
      pagerSent: false,
      pagerDutySent: false,
      opsgenieSent: false,
      realAuditorNotified: false,
      realRegulatorNotified: false,
      realStakeholderNotified: false,
      realApproverNotified: false,
      realCustomerNotified: false,
      productionV2Activated: false,
      readOnly: true,
      governanceOnly: true,
      simulationOnly: true,
      activationBlocked: true,
      payloadIncluded: false,
      sensitiveDataIncluded: false,
      approvedForComplianceRollbackNoOp: true,
      approvedForV2ShutdownNoOp: true,
      approvedForNoRealRollbackEvidence: true,
      approvedForRealRollback: false,
      approvedForRealV2Shutdown: false,
      approvedForRealTrafficReversion: false,
      approvedForRealStorage: false,
      approvedForProductionV2: false,
      approvedForRouteToV2: false
    };
  }
}
