export enum FiscalRouteSandboxStatus {
  ROUTE_SANDBOX_BLUEPRINT_READY = 'ROUTE_SANDBOX_BLUEPRINT_READY',
  WALLED_GARDEN_ISOLATION_READY = 'WALLED_GARDEN_ISOLATION_READY',
  BLOCKED_FOR_REAL_SANDBOX_PROVISIONING = 'BLOCKED_FOR_REAL_SANDBOX_PROVISIONING',
  FAILED_SAFE = 'FAILED_SAFE'
}

export interface FiscalRouteSandboxInput {
  requestedBy?: string;
  companyId?: string;
  requestId?: string;
  sandboxPurpose?: string;
  targetTeam?: string;
  targetTenantScope?: string;
  metadata?: any;
  forceCreateRealSandbox?: boolean;
  forceCreateWalledGarden?: boolean;
  forceProvisionNetwork?: boolean;
  forceProvisionDatabase?: boolean;
  forceCreateTenantIsolation?: boolean;
  forceCallRealEndpoint?: boolean;
  forceCallLegacyHandler?: boolean;
  forceCallV2Handler?: boolean;
  forceCaptureRequest?: boolean;
  forceCaptureResponse?: boolean;
  forceCapturePayload?: boolean;
  forceDuplicateRequest?: boolean;
  forceMirrorRealTraffic?: boolean;
  forceEnableShadowTraffic?: boolean;
  forceExecuteRealCutover?: boolean;
  forceRouteToV2?: boolean;
  forceDisableLegacyRoute?: boolean;
  forceChangeTraffic?: boolean;
  forceInstallProxy?: boolean;
  forceInstallMiddleware?: boolean;
  forceInstallTap?: boolean;
  forceModifyAppUse?: boolean;
  forceModifyRouterUse?: boolean;
  forceActivateProductionV2?: boolean;
  forceActivateRelease?: boolean;
  forceCreateWorker?: boolean;
  forceCreateScheduler?: boolean;
  forceUnlockGate?: boolean;
  forceGrantRealAuthorization?: boolean;
  forceConnectRealDatabase?: boolean;
  forceExecuteDml?: boolean;
  forceExecuteDdl?: boolean;
  forceCallRealSefaz?: boolean;
  forceLoadRealCertificate?: boolean;
  forceReadRealPfx?: boolean;
  forceReadCertificatePassword?: boolean;
  forceUseRealCrypto?: boolean;
  forceSignRealXml?: boolean;
  forceGenerateRealPdf?: boolean;
}

export interface FiscalRouteSandboxResult {
  success: boolean;
  status: FiscalRouteSandboxStatus | string;
  validationExecuted: boolean;
  evaluationExecuted: boolean;
  decisionSimulated: boolean;
  sandboxBlueprintGenerated: boolean;
  walledGardenIsolationGenerated: boolean;
  networkPlanGenerated: boolean;
  tenantIsolationPlanGenerated: boolean;
  dataBoundaryPlanGenerated: boolean;
  noRuntimeExecutionEvidenceGenerated: boolean;
  syntheticOnlyContractGenerated: boolean;
  dependencyMatrixGenerated: boolean;
  go: boolean;
  noGo: boolean;
  blockers: string[];
  warnings: string[];
  routeSandboxBlueprintOnly: true;
  walledGardenIsolationOnly: true;
  syntheticOnlyContractOnly: true;
  sandboxCreated: false;
  walledGardenCreated: false;
  networkProvisioned: false;
  databaseProvisioned: false;
  tenantIsolationCreated: false;
  realRouteExecuted: false;
  realEndpointCalled: false;
  legacyHandlerCalled: false;
  v2HandlerCalled: false;
  requestCaptured: false;
  responseCaptured: false;
  payloadCaptured: false;
  requestDuplicated: false;
  realTrafficMirrored: false;
  shadowTrafficEnabled: false;
  cutoverExecuted: false;
  realRouteTransitionExecuted: false;
  routeToV2: false;
  routeToLegacy: true;
  trafficChanged: false;
  proxyInstalled: false;
  middlewareInstalled: false;
  tapInstalled: false;
  appUseModified: false;
  routerUseModified: false;
  productionV2Activated: false;
  releaseActivated: false;
  workersCreated: false;
  schedulersCreated: false;
  realExecutionGateUnlocked: false;
  realAuthorizationGranted: false;
  dmlExecuted: false;
  ddlExecuted: false;
  realDatabaseConnected: false;
  realSefazCalled: false;
  realCertificateLoaded: false;
  realPfxRead: false;
  certificatePasswordRead: false;
  realCryptoUsed: false;
  xmlSigned: false;
  pdfGenerated: false;
  readOnly: true;
  governanceOnly: true;
  simulationOnly: true;
  activationBlocked: true;
  payloadIncluded: false;
  sensitiveDataIncluded: false;
  approvedForRouteSandboxBlueprint: true;
  approvedForWalledGardenIsolation: true;
  approvedForSyntheticOnlyContract: true;
  approvedForRealSandboxProvisioning: false;
  approvedForRealRouteExecution: false;
  approvedForRealRouteTransition: false;
  approvedForProductionV2: false;
}
