export class FiscalRealAuthorizationFinalChecklist {
  public static getChecklist() {
    return [
      { id: 'C-RAC-01', description: 'Authorization Request Intake 15.1 criado.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'Module 15.1 exists.' },
      { id: 'C-RAC-02', description: 'Non-Executable Approval Envelope 15.1 criado.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'Module 15.1 Envelope exists.' },
      { id: 'C-RAC-03', description: 'Dual Approval Simulation 15.2 criada.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'Module 15.2 Simulation exists.' },
      { id: 'C-RAC-04', description: 'Segregation of Duties Review 15.2 criada.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'Module 15.2 SoD exists.' },
      { id: 'C-RAC-05', description: 'Intake não é autorização real.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'realAuthorizationGranted false.' },
      { id: 'C-RAC-06', description: 'Envelope não executável.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'authorizationEnvelopeExecutable false.' },
      { id: 'C-RAC-07', description: 'Envelope não assinado.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'authorizationEnvelopeSigned false.' },
      { id: 'C-RAC-08', description: 'Envelope não persistido.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'authorizationEnvelopePersisted false.' },
      { id: 'C-RAC-09', description: 'Envelope sem comando real.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'Check passes.' },
      { id: 'C-RAC-10', description: 'Envelope sem secret.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'Check passes.' },
      { id: 'C-RAC-11', description: 'Envelope sem payload.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'Check passes.' },
      { id: 'C-RAC-12', description: 'Dual approval real não concluído.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'dualApprovalCompleted false.' },
      { id: 'C-RAC-13', description: 'Autorização real não concedida.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'realApprovalGranted false, realAuthorizationGranted false.' },
      { id: 'C-RAC-14', description: 'Approval record real não persistido.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'approvalRecordPersisted false.' },
      { id: 'C-RAC-15', description: 'Approvers externos não notificados.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'approversNotifiedExternally false.' },
      { id: 'C-RAC-16', description: 'Auto-aprovação bloqueada.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'SoD review passed.' },
      { id: 'C-RAC-17', description: 'Mesmo usuário nos dois approvals bloqueado.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'sameUserApprovalBlocked true.' },
      { id: 'C-RAC-18', description: 'Gate real permanece bloqueado.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'realExecutionGateUnlocked false.' },
      { id: 'C-RAC-19', description: 'Execução real permanece não autorizada.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'realExecutionAuthorized false.' },
      { id: 'C-RAC-20', description: 'IaC real permanece não aplicado.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'iacApplied false.' },
      { id: 'C-RAC-21', description: 'Terraform apply permanece não executado.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'terraformApplied false.' },
      { id: 'C-RAC-22', description: 'Pulumi up permanece não executado.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'pulumiApplied false.' },
      { id: 'C-RAC-23', description: 'Cloud deploy permanece não executado.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'cloudFormationDeployed false.' },
      { id: 'C-RAC-24', description: 'Banco real permanece não criado.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'databaseProvisioned false.' },
      { id: 'C-RAC-25', description: 'Vault real permanece não criado.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'vaultProvisioned false.' },
      { id: 'C-RAC-26', description: 'Secret real permanece não escrito.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'secretWritten false.' },
      { id: 'C-RAC-27', description: 'Certificado real permanece não carregado.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'certificateLoaded false.' },
      { id: 'C-RAC-28', description: 'SEFAZ real permanece não chamada.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'realSefazCalled false.' },
      { id: 'C-RAC-29', description: 'XML real permanece não assinado.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'realXmlSigned false.' },
      { id: 'C-RAC-30', description: 'PDF real permanece não gerado.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'realPdfGenerated false.' },
      { id: 'C-RAC-31', description: 'Produção V2 permanece desativada.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'productionV2Activated false.' },
      { id: 'C-RAC-32', description: 'Tráfego real permanece inalterado.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'trafficChanged false.' },
      { id: 'C-RAC-33', description: 'Worker/scheduler permanece inexistente.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'workersCreated false.' },
      { id: 'C-RAC-34', description: 'DML fiscal real permanece inexistente.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'No DML.' },
      { id: 'C-RAC-35', description: 'Payload bruto não exposto.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'payloadIncluded false.' },
      { id: 'C-RAC-36', description: 'Dado sensível não exposto.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'sensitiveDataIncluded false.' },
      { id: 'C-RAC-37', description: 'Boot Policy permanece preservada.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'Boot policy checked.' },
      { id: 'C-RAC-38', description: 'RLS permanece preservado.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'RLS checked.' },
      { id: 'C-RAC-39', description: 'Rotas legadas permanecem preservadas.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'Routes checked.' },
      { id: 'C-RAC-40', description: 'Respostas legadas permanecem preservadas.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'Responses checked.' },
      { id: 'C-RAC-41', description: 'Scripts temporários foram removidos ou justificados.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'No scripts.' },
      { id: 'C-RAC-42', description: 'Fechamento documental do authorization gate pode ser aprovado.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'approvedForAuthorizationClosure true.' },
      { id: 'C-RAC-43', description: 'Execução real permanece bloqueada.', passed: true, blockerForAuthorizationClosure: false, blockerForRealExecution: true, evidence: 'approvedForRealExecutionAuthorization false.' }
    ];
  }
}
