import {
  FiscalProductionGoLiveCutoverClosureInput,
  FiscalProductionGoLiveCutoverClosureResult,
  FiscalProductionGoLiveCutoverClosureStatus
} from './FiscalProductionGoLiveCutoverClosureTypes';
import { FiscalProductionGoLiveCutoverClosureValidator } from './FiscalProductionGoLiveCutoverClosureValidator';
import { FiscalProductionGoLiveCutoverClosureEvaluationService } from './FiscalProductionGoLiveCutoverClosureEvaluationService';

export class FiscalProductionGoLiveCutoverClosureDecisionService {
  public static simulateDecision(input: FiscalProductionGoLiveCutoverClosureInput): FiscalProductionGoLiveCutoverClosureResult {
    const errors = FiscalProductionGoLiveCutoverClosureValidator.validate(input);
    const warnings = FiscalProductionGoLiveCutoverClosureEvaluationService.evaluate(input);

    const isBlocked = errors.length > 0;

    return {
      success: !isBlocked,
      status: isBlocked ? FiscalProductionGoLiveCutoverClosureStatus.BLOCKED_FOR_REAL_GO_LIVE_CLOSURE_OR_ACTIVATION : FiscalProductionGoLiveCutoverClosureStatus.PRODUCTION_GO_LIVE_CUTOVER_CLOSURE_READY,
      validationExecuted: true,
      evaluationExecuted: true,
      decisionSimulated: true,
      closureInventoryGenerated: true,
      finalChecklistGenerated: true,
      evidencePackageGenerated: true,
      noActivationHandoffGenerated: true,
      postClosureRoadmapGenerated: true,
      finalBlockersGenerated: true,
      finalRisksGenerated: true,
      go: false,
      noGo: true,
      blockers: errors,
      warnings,
      productionGoLiveCutoverClosureOnly: true,
      finalNoActivationEvidenceOnly: true,
      noActivationHandoffOnly: true,
      realClosureExecuted: false,
      realGoLiveConcluded: false,
      realCutoverExecuted: false,
      realAuthorizationGranted: false,
      realHandoffConcluded: false,
      realExecutionGateUnlocked: false,
      realAuthorizationTokenIssued: false,
      productionV2Activated: false,
      routeToV2: false,
      routeToLegacy: true,
      trafficChanged: false,
      realLoadBalancerSwitched: false,
      realDnsChanged: false,
      realProxyInstalled: false,
      realMiddlewareInstalled: false,
      realTapInstalled: false,
      realShadowTrafficEnabled: false,
      realRequestCaptured: false,
      realResponseCaptured: false,
      realPayloadCaptured: false,
      realLegacyHandlerCalled: false,
      realV2HandlerCalled: false,
      realRollbackExecuted: false,
      realAbortExecuted: false,
      realFallbackExecuted: false,
      realReleaseExecuted: false,
      realRolloutExecuted: false,
      realCanaryActivated: false,
      realShutdownExecuted: false,
      realRuntimeStarted: false,
      realQueueStarted: false,
      realJobEnqueued: false,
      realWorkerDispatched: false,
      realShellCommandExecuted: false,
      realDatabaseConnected: false,
      dmlExecuted: false,
      ddlExecuted: false,
      realSefazCalled: false,
      realPayloadRead: false,
      realXmlRead: false,
      realPdfRead: false,
      realPfxRead: false,
      realCertificateRead: false,
      certificatePasswordRead: false,
      realSecretRead: false,
      privateKeyRead: false,
      tokenRead: false,
      realCryptoUsed: false,
      realHashCalculated: false,
      xmlSigned: false,
      pdfGenerated: false,
      fileSystemWritten: false,
      externalStorageUploaded: false,
      realIncidentCreated: false,
      realTicketCreated: false,
      realRemediationExecuted: false,
      webhookSent: false,
      slackSent: false,
      whatsappSent: false,
      emailSent: false,
      pagerSent: false,
      pagerDutySent: false,
      opsgenieSent: false,
      realStakeholderNotified: false,
      realApproverNotified: false,
      realCustomerNotified: false,
      realOperatorNotified: false,
      readOnly: true,
      governanceOnly: true,
      simulationOnly: true,
      activationBlocked: true,
      payloadIncluded: false,
      sensitiveDataIncluded: false,
      approvedForClosureDocumentation: true,
      approvedForFinalNoActivationEvidence: true,
      approvedForNoActivationHandoff: true,
      approvedForRealGoLive: false,
      approvedForRealCutover: false,
      approvedForRealAuthorization: false,
      approvedForProductionV2: false,
      approvedForRouteToV2: false
    };
  }
}
