import { Router } from "express";
import { FiscalDocumentController } from "./FiscalDocumentController";
import { NfeController } from "./NfeController";
import { NfceController } from "./NfceController";
import { DanfeController } from "./DanfeController";
import { SefazProtocolController } from "./SefazProtocolController";
import { requireFiscalAuth } from "./helpers";
import { sandboxRoutes } from "./sandbox.routes";
import { fiscalSandboxPersistenceRoutes } from "./fiscalSandboxPersistence.routes";
import { fiscalSandboxReplayBridgeRoutes } from "./fiscalSandboxReplayBridge.routes";
import { fiscalSandboxReviewRoutes } from "./fiscalSandboxReview.routes";
import { fiscalSandboxIntegrityRoutes } from "./fiscalSandboxIntegrity.routes";
import { fiscalSandboxEvidenceRoutes } from "./fiscalSandboxEvidence.routes";
import { fiscalSandboxClosureRoutes } from "./fiscalSandboxClosure.routes";
import { fiscalShadowMirrorRoutes } from "./fiscalShadowMirror.routes";
import { fiscalShadowMirrorSimulationRoutes } from "./fiscalShadowMirrorSimulation.routes";
import { fiscalShadowMirrorCaptureRoutes } from "./fiscalShadowMirrorCapture.routes";
import { fiscalShadowMirrorPassiveTapRoutes } from "./fiscalShadowMirrorPassiveTap.routes";
import { fiscalSafeShapeMiddlewareRoutes } from "./fiscalSafeShapeMiddleware.routes";
import { fiscalShadowMirrorTelemetryRoutes } from "./fiscalShadowMirrorTelemetry.routes";
import { fiscalShadowMirrorGovernanceRoutes } from "./fiscalShadowMirrorGovernance.routes";
import { fiscalLoadPlanningRoutes } from "./fiscalLoadPlanning.routes";
import { fiscalLoadRunnerRoutes } from "./fiscalLoadRunner.routes";
import { fiscalLoadPlanningClosureRoutes } from "./fiscalLoadPlanningClosure.routes";
import { fiscalReleaseGateRoutes } from "./fiscalReleaseGate.routes";
import { fiscalRollbackPlanningRoutes } from "./fiscalRollbackPlanning.routes";
import { fiscalReleaseReadinessClosureRoutes } from "./fiscalReleaseReadinessClosure.routes";
import { fiscalHomologationBlueprintRoutes } from "./fiscalHomologationBlueprint.routes";
import { fiscalHomologationMockRoutes } from "./fiscalHomologationMock.routes";
import { fiscalHomologationReviewRoutes } from "./fiscalHomologationReview.routes";
import { fiscalHomologationClosureRoutes } from "./fiscalHomologationClosure.routes";
import { fiscalHomologationTransitionRoutes } from "./fiscalHomologationTransition.routes";
import { fiscalDedicatedHomologationRoutes } from "./fiscalDedicatedHomologation.routes";
import { fiscalDedicatedProvisioningRoutes } from "./fiscalDedicatedProvisioning.routes";
import { fiscalDedicatedSimulationRoutes } from "./fiscalDedicatedSimulation.routes";
import { fiscalDedicatedReplayRoutes } from "./fiscalDedicatedReplay.routes";
import { fiscalDedicatedClosureRoutes } from "./fiscalDedicatedClosure.routes";
import { fiscalRealProvisioningBlueprintRoutes } from "./fiscalRealProvisioningBlueprint.routes";
import { fiscalRealProvisioningRoutes } from "./fiscalRealProvisioning.routes";
import { fiscalRealProvisioningSecurityRoutes } from "./fiscalRealProvisioningSecurity.routes";
import { fiscalRealChangeWindowRoutes } from "./fiscalRealChangeWindow.routes";
import { fiscalRealProvisioningClosureRoutes } from "./fiscalRealProvisioningClosure.routes";
import { fiscalRealExecutionGateRoutes } from "./fiscalRealExecutionGate.routes";
import { fiscalRealUnlockRoutes } from "./fiscalRealUnlock.routes";
import { fiscalRealActionPlanRoutes } from "./fiscalRealActionPlan.routes";
import { fiscalRealExecutionGateClosureRoutes } from "./fiscalRealExecutionGateClosure.routes";
import { fiscalRealExecutionPreparationRoutes } from "./fiscalRealExecutionPreparation.routes";
import { fiscalRealCommandManifestRoutes } from "./fiscalRealCommandManifest.routes";
import { fiscalRealPreflightRoutes } from "./fiscalRealPreflight.routes";
import { fiscalRealExecutionPreparationClosureRoutes } from "./fiscalRealExecutionPreparationClosure.routes";
import { fiscalRealAuthorizationRoutes } from "./fiscalRealAuthorization.routes";
import { fiscalRealDualApprovalRoutes } from "./fiscalRealDualApproval.routes";
import { fiscalRealAuthorizationClosureRoutes } from "./fiscalRealAuthorizationClosure.routes";
import { fiscalRealApprovalRecordRoutes } from "./fiscalRealApprovalRecord.routes";
import { fiscalRealApprovalRecordDryRunRoutes } from "./fiscalRealApprovalRecordDryRun.routes";
import { fiscalRealApprovalRecordClosureRoutes } from "./fiscalRealApprovalRecordClosure.routes";
import { fiscalRealApprovalPersistenceGateRoutes } from "./fiscalRealApprovalPersistenceGate.routes";
import { fiscalRealApprovalSchemaDryRunRoutes } from "./fiscalRealApprovalSchemaDryRun.routes";
import { fiscalRealApprovalDmlDryRunRoutes } from "./fiscalRealApprovalDmlDryRun.routes";
import fiscalRealApprovalMockSignatureRoutes from "./fiscalRealApprovalMockSignature.routes";
import fiscalRealApprovalDualClosureRoutes from "./fiscalRealApprovalDualClosure.routes";
import fiscalLegalAuditTrailRoutes from "./fiscalLegalAuditTrail.routes";
import fiscalLegalAuditSchemaDryRunRoutes from "./fiscalLegalAuditSchemaDryRun.routes";
import fiscalLegalAuditEventDryRunRoutes from "./fiscalLegalAuditEventDryRun.routes";
import fiscalLegalAuditImmutabilityRoutes from "./fiscalLegalAuditImmutability.routes";
import fiscalLegalAuditClosureRoutes from "./fiscalLegalAuditClosure.routes";
import fiscalProductionActivationRoutes from "./fiscalProductionActivation.routes";
import fiscalProductionCanaryDryRunRoutes from "./fiscalProductionCanaryDryRun.routes";
import fiscalProductionReleaseGatewayRoutes from "./fiscalProductionReleaseGateway.routes";
import fiscalProductionRollbackKillSwitchRoutes from "./fiscalProductionRollbackKillSwitch.routes";
import fiscalProductionDualRunRoutes from "./fiscalProductionDualRun.routes";
import fiscalProductionActivationClosureRoutes from "./fiscalProductionActivationClosure.routes";
import fiscalOperationalHandoffRoutes from "./fiscalOperationalHandoff.routes";
import fiscalOperationalObservabilityDryRunRoutes from "./fiscalOperationalObservabilityDryRun.routes";
import fiscalOperationalCommitteeDryRunRoutes from "./fiscalOperationalCommitteeDryRun.routes";
import fiscalOperationalHandoffClosureRoutes from "./fiscalOperationalHandoffClosure.routes";
import fiscalLegalSignOffRoutes from "./fiscalLegalSignOff.routes";
import fiscalLegalSignatureDryRunRoutes from "./fiscalLegalSignatureDryRun.routes";
import fiscalLegalCommitteeDryRunRoutes from "./fiscalLegalCommitteeDryRun.routes";
import fiscalLegalSignOffClosureRoutes from "./fiscalLegalSignOffClosure.routes";
import fiscalFinalGoLiveRoutes from "./fiscalFinalGoLive.routes";
import fiscalFinalGoLiveGateDryRunRoutes from "./fiscalFinalGoLiveGateDryRun.routes";
import fiscalFinalGoLiveClosureRoutes from "./fiscalFinalGoLiveClosure.routes";
import fiscalRouteTransitionRoutes from "./fiscalRouteTransition.routes";
import fiscalRouteProxyDryRunRoutes from "./fiscalRouteProxyDryRun.routes";
import fiscalRouteCanaryShadowRoutes from "./fiscalRouteCanaryShadow.routes";
import fiscalRouteCutoverRoutes from "./fiscalRouteCutover.routes";
import fiscalSyntheticRouteDryRunRoutes from "./fiscalSyntheticRouteDryRun.routes";
import fiscalRouteSandboxRoutes from "./fiscalRouteSandbox.routes";
import fiscalRouteTransitionClosureRoutes from "./fiscalRouteTransitionClosure.routes";
import fiscalProductionDeploymentIsolationRoutes from "./fiscalProductionDeploymentIsolation.routes";
import fiscalReleaseArtifactDryRunRoutes from "./fiscalReleaseArtifactDryRun.routes";
import fiscalProductionCutoverApprovalRoutes from "./fiscalProductionCutoverApproval.routes";
import fiscalProductionPreflightRoutes from "./fiscalProductionPreflight.routes";
import fiscalProductionCanaryTrafficSwitchRoutes from "./fiscalProductionCanaryTrafficSwitch.routes";
import fiscalProductionDeploymentClosureRoutes from "./fiscalProductionDeploymentClosure.routes";
import fiscalProductionExecutionBoundaryRoutes from "./fiscalProductionExecutionBoundary.routes";
import fiscalProductionAuthorizationRequestRoutes from "./fiscalProductionAuthorizationRequest.routes";
import fiscalProductionCommitteeDeliberationRoutes from "./fiscalProductionCommitteeDeliberation.routes";
import fiscalProductionFinalAuthorizationRoutes from "./fiscalProductionFinalAuthorization.routes";
import fiscalProductionExecutionAuthorizationClosureRoutes from "./fiscalProductionExecutionAuthorizationClosure.routes";
import fiscalProductionExecutionOrchestrationRoutes from "./fiscalProductionExecutionOrchestration.routes";
import fiscalProductionRuntimeStepDryRunRoutes from "./fiscalProductionRuntimeStepDryRun.routes";
import fiscalProductionRuntimeQueueUnlockRoutes from "./fiscalProductionRuntimeQueueUnlock.routes";
import fiscalProductionRuntimeExecutionGraphRoutes from "./fiscalProductionRuntimeExecutionGraph.routes";
import fiscalProductionRuntimeExecutionClosureRoutes from "./fiscalProductionRuntimeExecutionClosure.routes";
import fiscalProductionCutoverGovernanceRoutes from "./fiscalProductionCutoverGovernance.routes";
import fiscalProductionRouteReroutingClosureRoutes from "./fiscalProductionRouteReroutingClosure.routes";
import fiscalProductionRollbackAbortRoutes from "./fiscalProductionRollbackAbort.routes";
import fiscalProductionRolloutApprovalRoutes from "./fiscalProductionRolloutApproval.routes";
import fiscalProductionCutoverClosureRoutes from "./fiscalProductionCutoverClosure.routes";
import fiscalDay2OperationsRoutes from "./fiscalDay2Operations.routes";
import fiscalDay2SupportAccessRoutes from "./fiscalDay2SupportAccess.routes";
import fiscalDay2IncidentRunbookRoutes from "./fiscalDay2IncidentRunbook.routes";
import fiscalDay2ObservabilityDriftRoutes from "./fiscalDay2ObservabilityDrift.routes";
import fiscalDay2OperationsClosureRoutes from "./fiscalDay2OperationsClosure.routes";
import fiscalProductionOperationsTransitionRoutes from "./fiscalProductionOperationsTransition.routes";
import fiscalProductionActivationConsentRoutes from "./fiscalProductionActivationConsent.routes";
import fiscalProductionAuthorizationDeliberationRoutes from "./fiscalProductionAuthorizationDeliberation.routes";
import fiscalProductionTrafficSwitchRoutes from "./fiscalProductionTrafficSwitch.routes";
import fiscalProductionOperationsTransitionClosureRoutes from "./fiscalProductionOperationsTransitionClosure.routes";
import fiscalProductionBaselineCutoverRoutes from "./fiscalProductionBaselineCutover.routes";
import fiscalProductionBaselineApprovalRoutes from "./fiscalProductionBaselineApproval.routes";
import fiscalProductionBaselineOrchestrationRoutes from "./fiscalProductionBaselineOrchestration.routes";
import fiscalProductionRollbackReversionRoutes from "./fiscalProductionRollbackReversion.routes";
import fiscalProductionBaselineCutoverClosureRoutes from "./fiscalProductionBaselineCutoverClosure.routes";
import fiscalProductionOperationsReadinessRoutes from "./fiscalProductionOperationsReadiness.routes";
import fiscalProductionOperationsAccessHandoffRoutes from "./fiscalProductionOperationsAccessHandoff.routes";
import fiscalProductionOperationsSupportRunbookRoutes from "./fiscalProductionOperationsSupportRunbook.routes";
import fiscalProductionOperationsObservabilityRoutes from "./fiscalProductionOperationsObservability.routes";
import fiscalProductionOperationsReadinessClosureRoutes from "./fiscalProductionOperationsReadinessClosure.routes";
import fiscalProductionOperationsSignatureGovernanceRoutes from "./fiscalProductionOperationsSignatureGovernance.routes";
import fiscalProductionOperationsStakeholderSignatureRoutes from "./fiscalProductionOperationsStakeholderSignature.routes";
import fiscalProductionOperationsSignatureCommitteeRoutes from "./fiscalProductionOperationsSignatureCommittee.routes";
import fiscalProductionOperationsSignatureActivationGateRoutes from "./fiscalProductionOperationsSignatureActivationGate.routes";
import fiscalProductionOperationsSignatureGovernanceClosureRoutes from "./fiscalProductionOperationsSignatureGovernanceClosure.routes";
import fiscalProductionActivationControlPlaneRoutes from "./fiscalProductionActivationControlPlane.routes";
import fiscalProductionActivationApprovalRoutes from "./fiscalProductionActivationApproval.routes";
import fiscalProductionActivationGateUnlockRoutes from "./fiscalProductionActivationGateUnlock.routes";
import fiscalProductionCanaryRampRoutes from "./fiscalProductionCanaryRamp.routes";
import fiscalProductionActivationControlPlaneClosureRoutes from "./fiscalProductionActivationControlPlaneClosure.routes";
import fiscalProductionPhysicalExecutionFirewallRoutes from "./fiscalProductionPhysicalExecutionFirewall.routes";
import fiscalProductionExecutionBoundaryVerificationRoutes from "./fiscalProductionExecutionBoundaryVerification.routes";
import fiscalProductionExecutionFirewallApprovalRoutes from "./fiscalProductionExecutionFirewallApproval.routes";
import fiscalProductionExecutionCutoverDenialRoutes from "./fiscalProductionExecutionCutoverDenial.routes";
import fiscalProductionPhysicalExecutionFirewallClosureRoutes from "./fiscalProductionPhysicalExecutionFirewallClosure.routes";
import fiscalProductionEvidenceVaultGovernanceRoutes from "./fiscalProductionEvidenceVaultGovernance.routes";
import fiscalProductionComplianceAuditGovernanceRoutes from "./fiscalProductionComplianceAuditGovernance.routes";
import fiscalProductionRegulatoryFilingRoutes from "./fiscalProductionRegulatoryFiling.routes";
import fiscalProductionComplianceFindingRoutes from "./fiscalProductionComplianceFinding.routes";
import fiscalProductionComplianceReleaseGatekeeperRoutes from "./fiscalProductionComplianceReleaseGatekeeper.routes";
import { fiscalProductionComplianceRollbackShutdownRoutes } from "./fiscalProductionComplianceRollbackShutdown.routes";
import { fiscalProductionComplianceAuditClosureRoutes } from "./fiscalProductionComplianceAuditClosure.routes";
import { fiscalProductionGoLiveCutoverRoutes } from "./fiscalProductionGoLiveCutover.routes";
import { fiscalProductionTrafficRoutingRoutes } from "./fiscalProductionTrafficRouting.routes";
import { fiscalProductionGoLiveRollbackRoutes } from "./fiscalProductionGoLiveRollback.routes";
import { fiscalProductionGoLiveFinalApprovalRoutes } from "./fiscalProductionGoLiveFinalApproval.routes";
import { fiscalProductionGoLiveCutoverClosureRoutes } from "./fiscalProductionGoLiveCutoverClosure.routes";
import { fiscalProductionPostGoLiveStabilizationRoutes } from "./fiscalProductionPostGoLiveStabilization.routes";
import { fiscalProductionPostGoLiveIncidentReadinessRoutes } from "./fiscalProductionPostGoLiveIncidentReadiness.routes";
import { fiscalProductionPostGoLiveObservabilityRoutes } from "./fiscalProductionPostGoLiveObservability.routes";
import { fiscalProductionPostGoLiveRemediationRoutes } from "./fiscalProductionPostGoLiveRemediation.routes";
import { fiscalProductionPostGoLiveStabilizationClosureRoutes } from "./fiscalProductionPostGoLiveStabilizationClosure.routes";
import { fiscalProductionTrafficArchitectureRoutes } from "./fiscalProductionTrafficArchitecture.routes";
import { fiscalProductionLoadBalancerDnsRoutes } from "./fiscalProductionLoadBalancerDns.routes";
import { fiscalProductionProxyShadowRoutes } from "./fiscalProductionProxyShadow.routes";
import { fiscalProductionRoutePromotionRoutes } from "./fiscalProductionRoutePromotion.routes";
import { fiscalProductionTrafficArchitectureClosureRoutes } from "./fiscalProductionTrafficArchitectureClosure.routes";
import { fiscalProductionRuntimeOrchestrationRoutes } from "./fiscalProductionRuntimeOrchestration.routes";
import { fiscalProductionQueueWorkerRoutes } from "./fiscalProductionQueueWorker.routes";
import { fiscalProductionSchedulerCommandRoutes } from "./fiscalProductionSchedulerCommand.routes";
import { fiscalProductionDatabasePersistenceRoutes } from "./fiscalProductionDatabasePersistence.routes";
import { fiscalProductionExternalIntegrationRoutes } from "./fiscalProductionExternalIntegration.routes";
import { fiscalProductionRuntimeOrchestrationClosureRoutes } from "./fiscalProductionRuntimeOrchestrationClosure.routes";
import { fiscalProductionFinalGoLiveCommandCenterRoutes } from "./fiscalProductionFinalGoLiveCommandCenter.routes";
import { fiscalProductionFinalGoLiveReadinessRoutes } from "./fiscalProductionFinalGoLiveReadiness.routes";
import { fiscalProductionFinalGoLiveActivationCommandRoutes } from "./fiscalProductionFinalGoLiveActivationCommand.routes";
import { fiscalProductionFinalGoLiveCommandRollbackRoutes } from "./fiscalProductionFinalGoLiveCommandRollback.routes";
import { fiscalProductionFinalStateLedgerRoutes } from "./fiscalProductionFinalStateLedger.routes";
import { fiscalProductionFinalStateSnapshotRoutes } from "./fiscalProductionFinalStateSnapshot.routes";
import { fiscalProductionFinalStateIntegrityRoutes } from "./fiscalProductionFinalStateIntegrity.routes";
import { fiscalProductionFinalStateDisclosureRoutes } from "./fiscalProductionFinalStateDisclosure.routes";
import { fiscalProductionFinalStateLedgerClosureRoutes } from "./fiscalProductionFinalStateLedgerClosure.routes";
import { fiscalProductionCorporateGovernanceArchiveRoutes } from "./fiscalProductionCorporateGovernanceArchive.routes";
import { fiscalProductionCorporateBoardReviewRoutes } from "./fiscalProductionCorporateBoardReview.routes";
import { fiscalProductionCorporateGovernanceArchiveClosureRoutes } from "./fiscalProductionCorporateGovernanceArchiveClosure.routes";
import { fiscalProductionGovernanceRetentionRoutes } from "./fiscalProductionGovernanceRetention.routes";
import { fiscalProductionRetentionCustodyAttestationRoutes } from "./fiscalProductionRetentionCustodyAttestation.routes";
import { fiscalProductionRetentionLifecycleDriftRoutes } from "./fiscalProductionRetentionLifecycleDrift.routes";
import { fiscalProductionRetentionAccessDisclosureRoutes } from "./fiscalProductionRetentionAccessDisclosure.routes";
import { fiscalProductionFinalGoLiveCommandCenterClosureRoutes } from "./fiscalProductionFinalGoLiveCommandCenterClosure.routes";
import fiscalProductionEvidenceIntakeRoutes from "./fiscalProductionEvidenceIntake.routes";
import fiscalProductionEvidenceIntegrityCustodyRoutes from "./fiscalProductionEvidenceIntegrityCustody.routes";
import fiscalProductionEvidenceDisclosureRoutes from "./fiscalProductionEvidenceDisclosure.routes";
import fiscalProductionEvidenceVaultClosureRoutes from "./fiscalProductionEvidenceVaultClosure.routes";
import { fiscalProductionGovernanceRetentionDormancyClosureRoutes } from "./fiscalProductionGovernanceRetentionDormancyClosure.routes";
import { fiscalProductionSystemWideNonOperationalSealRoutes } from "./fiscalProductionSystemWideNonOperationalSeal.routes";
import { fiscalProductionCrossDomainSealEvidenceRoutes } from "./fiscalProductionCrossDomainSealEvidence.routes";
import { fiscalProductionFinalHandshakeRoutes } from "./fiscalProductionFinalHandshake.routes";
import fiscalProductionSealHandoffDisconnectionRoutes from "./fiscalProductionSealHandoffDisconnection.routes";
import fiscalProductionSystemWideNonOperationalSealClosureRoutes from "./fiscalProductionSystemWideNonOperationalSealClosure.routes";
import fiscalProductionPostSealDormantStateRoutes from "./fiscalProductionPostSealDormantState.routes";
import fiscalProductionReentryAttemptDenialRoutes from "./fiscalProductionReentryAttemptDenial.routes";
import fiscalProductionDormantStateDriftVerificationRoutes from "./fiscalProductionDormantStateDriftVerification.routes";
import fiscalProductionDormantStateFinalReviewRoutes from "./fiscalProductionDormantStateFinalReview.routes";
import fiscalProductionPostSealDormantStateClosureRoutes from "./fiscalProductionPostSealDormantStateClosure.routes";
import { shadowRoutes } from "./shadow.routes";
import { shadowDashboardRoutes } from "./shadowDashboard.routes";
import { fiscalCanaryRoutes } from "./fiscalCanary.routes";
import { fiscalCanaryControlRoutes } from "./fiscalCanaryControl.routes";

const router = Router();

// Middleware de autenticação obrigatória para todas as rotas fiscal-v2
router.use(requireFiscalAuth);

// Instanciação dos controllers do módulo fiscal
const fiscalDocumentController = new FiscalDocumentController();
const nfeController = new NfeController();
const nfceController = new NfceController();
const danfeController = new DanfeController();
const sefazProtocolController = new SefazProtocolController();

/**
 * Rotas de Governança Canary (Sprint 4.17, 4.18, 4.20, 4.21, 4.22, 4.23, 4.24, 4.25)
 */
import { fiscalCanaryEvidenceRoutes } from "./fiscalCanaryEvidence.routes";
import { fiscalCanaryCockpitRoutes } from "./fiscalCanaryCockpit.routes";
import { fiscalCanaryPreActivationRoutes } from "./fiscalCanaryPreActivation.routes";
import { fiscalCanaryRuntimeRoutes } from "./fiscalCanaryRuntime.routes";
import { fiscalCanaryRouteMappingRoutes } from "./fiscalCanaryRouteMapping.routes";
import { fiscalShadowProxyRoutes } from "./fiscalShadowProxy.routes";
import { fiscalV2ReadinessRoutes } from "./fiscalV2Readiness.routes";
import { fiscalShadowTapRoutes } from "./fiscalShadowTap.routes";
import { fiscalShadowReplayRoutes } from "./fiscalShadowReplay.routes";

router.use("/canary/readiness", fiscalV2ReadinessRoutes);
router.use("/canary/tap/replay", fiscalShadowReplayRoutes);
router.use("/canary/tap", fiscalShadowTapRoutes);
router.use("/canary/proxy", fiscalShadowProxyRoutes);
router.use("/canary/routes", fiscalCanaryRouteMappingRoutes);
router.use("/canary/runtime", fiscalCanaryRuntimeRoutes);
router.use("/canary/pre-activation", fiscalCanaryPreActivationRoutes);
router.use("/canary/cockpit", fiscalCanaryCockpitRoutes);
router.use("/canary/evidence", fiscalCanaryEvidenceRoutes);
router.use("/canary/control", fiscalCanaryControlRoutes);
router.use("/canary", fiscalCanaryRoutes);

/**
 * Rotas de Shadow Comparison (Sprint 4.11)
 */
router.use("/shadow/dashboard", shadowDashboardRoutes);
router.use("/shadow", shadowRoutes);

/**
 * Rotas de Sandbox (Sprint 4.10)
 * Devem ser montadas antes das rotas parametrizadas
 */
router.use("/sandbox", sandboxRoutes);
router.use("/sandbox-persistence", fiscalSandboxPersistenceRoutes);
router.use("/sandbox-replay-bridge", fiscalSandboxReplayBridgeRoutes);
router.use("/sandbox-review", fiscalSandboxReviewRoutes);
router.use("/sandbox-integrity", fiscalSandboxIntegrityRoutes);
router.use("/sandbox-evidence", fiscalSandboxEvidenceRoutes);
router.use("/sandbox-closure", fiscalSandboxClosureRoutes);
router.use("/shadow-mirror/simulation", fiscalShadowMirrorSimulationRoutes);
router.use("/shadow-mirror/capture", fiscalShadowMirrorCaptureRoutes);
router.use("/shadow-mirror/passive-tap", fiscalShadowMirrorPassiveTapRoutes);
router.use("/shadow-mirror/safe-middleware", fiscalSafeShapeMiddlewareRoutes);
router.use("/shadow-mirror/telemetry", fiscalShadowMirrorTelemetryRoutes);
router.use("/shadow-mirror/governance", fiscalShadowMirrorGovernanceRoutes);
router.use("/shadow-mirror", fiscalShadowMirrorRoutes);
router.use("/load-planning/runner", fiscalLoadRunnerRoutes);
router.use("/load-planning/closure", fiscalLoadPlanningClosureRoutes);
router.use("/load-planning", fiscalLoadPlanningRoutes);
router.use("/release-gate/closure", fiscalReleaseReadinessClosureRoutes);
router.use("/release-gate/rollback", fiscalRollbackPlanningRoutes);
router.use("/release-gate", fiscalReleaseGateRoutes);
router.use("/homologation-blueprint/mock", fiscalHomologationMockRoutes);
router.use("/homologation-blueprint/review", fiscalHomologationReviewRoutes);
router.use("/homologation-blueprint/closure", fiscalHomologationClosureRoutes);
router.use("/homologation-blueprint/transition", fiscalHomologationTransitionRoutes);
router.use("/homologation-blueprint", fiscalHomologationBlueprintRoutes);
router.use("/dedicated-homologation/provisioning", fiscalDedicatedProvisioningRoutes);
router.use("/dedicated-homologation/simulation", fiscalDedicatedSimulationRoutes);
router.use("/dedicated-homologation/replay", fiscalDedicatedReplayRoutes);
router.use("/dedicated-homologation/closure", fiscalDedicatedClosureRoutes);
router.use("/dedicated-homologation/real-blueprint", fiscalRealProvisioningBlueprintRoutes);
router.use("/dedicated-homologation/real-execution-gate/action-plan", fiscalRealActionPlanRoutes);
router.use("/dedicated-homologation/real-execution-gate/closure", fiscalRealExecutionGateClosureRoutes);
router.use("/dedicated-homologation/real-execution-gate/unlock", fiscalRealUnlockRoutes);
router.use("/dedicated-homologation/real-execution-gate", fiscalRealExecutionGateRoutes);
router.use("/dedicated-homologation/real-execution-preparation/command-manifest", fiscalRealCommandManifestRoutes);
router.use("/dedicated-homologation/real-execution-preparation/preflight", fiscalRealPreflightRoutes);
router.use("/dedicated-homologation/real-execution-preparation/closure", fiscalRealExecutionPreparationClosureRoutes);
router.use("/dedicated-homologation/real-execution-preparation", fiscalRealExecutionPreparationRoutes);
router.use("/dedicated-homologation/production-activation/closure", fiscalProductionActivationClosureRoutes);
router.use("/dedicated-homologation/operational-handoff/closure", fiscalOperationalHandoffClosureRoutes);
router.use("/dedicated-homologation/operational-handoff/committee-dry-run", fiscalOperationalCommitteeDryRunRoutes);
router.use("/dedicated-homologation/operational-handoff/observability-dry-run", fiscalOperationalObservabilityDryRunRoutes);
router.use("/dedicated-homologation/operational-handoff", fiscalOperationalHandoffRoutes);
router.use("/dedicated-homologation/legal-signoff/committee-dry-run", fiscalLegalCommitteeDryRunRoutes);
router.use("/dedicated-homologation/legal-signoff/signature-dry-run", fiscalLegalSignatureDryRunRoutes);
router.use("/dedicated-homologation/legal-signoff/closure", fiscalLegalSignOffClosureRoutes);
router.use("/dedicated-homologation/legal-signoff", fiscalLegalSignOffRoutes);
router.use("/dedicated-homologation/final-golive/gate-dry-run", fiscalFinalGoLiveGateDryRunRoutes);
router.use("/dedicated-homologation/final-golive/closure", fiscalFinalGoLiveClosureRoutes);
router.use("/dedicated-homologation/final-golive", fiscalFinalGoLiveRoutes);
router.use("/dedicated-homologation/route-transition/proxy-dry-run", fiscalRouteProxyDryRunRoutes);
router.use("/dedicated-homologation/route-transition/canary-shadow-dry-run", fiscalRouteCanaryShadowRoutes);
router.use("/dedicated-homologation/route-transition/cutover-dry-run", fiscalRouteCutoverRoutes);
router.use("/dedicated-homologation/route-transition/synthetic-route-dry-run", fiscalSyntheticRouteDryRunRoutes);
router.use("/dedicated-homologation/route-transition/route-sandbox", fiscalRouteSandboxRoutes);
router.use("/dedicated-homologation/route-transition/closure", fiscalRouteTransitionClosureRoutes);
router.use("/dedicated-homologation/route-transition", fiscalRouteTransitionRoutes);
router.use("/dedicated-homologation/production-execution-orchestration/closure", fiscalProductionRuntimeExecutionClosureRoutes);
router.use("/dedicated-homologation/production-execution-orchestration/execution-graph-dry-run", fiscalProductionRuntimeExecutionGraphRoutes);
router.use("/dedicated-homologation/production-execution-orchestration/queue-unlock-dry-run", fiscalProductionRuntimeQueueUnlockRoutes);
router.use("/dedicated-homologation/production-execution-orchestration/runtime-step-dry-run", fiscalProductionRuntimeStepDryRunRoutes);
router.use("/dedicated-homologation/production-execution-orchestration", fiscalProductionExecutionOrchestrationRoutes);
router.use("/dedicated-homologation/production-cutover-governance/route-rerouting-closure", fiscalProductionRouteReroutingClosureRoutes);
router.use("/dedicated-homologation/production-cutover-governance/rollback-abort-dry-run", fiscalProductionRollbackAbortRoutes);
router.use("/dedicated-homologation/production-cutover-governance/rollout-approval-dry-run", fiscalProductionRolloutApprovalRoutes);
router.use("/dedicated-homologation/production-cutover-governance/closure", fiscalProductionCutoverClosureRoutes);
router.use("/dedicated-homologation/day2-operations-governance/closure", fiscalDay2OperationsClosureRoutes);
router.use("/dedicated-homologation/day2-operations-governance/observability-drift-dry-run", fiscalDay2ObservabilityDriftRoutes);
router.use("/dedicated-homologation/day2-operations-governance/incident-runbook-dry-run", fiscalDay2IncidentRunbookRoutes);
router.use("/dedicated-homologation/day2-operations-governance/support-access-dry-run", fiscalDay2SupportAccessRoutes);
router.use("/dedicated-homologation/day2-operations-governance", fiscalDay2OperationsRoutes);
router.use("/dedicated-homologation/production-operations-readiness/observability-telemetry-dry-run", fiscalProductionOperationsObservabilityRoutes);
router.use("/dedicated-homologation/production-operations-readiness/closure", fiscalProductionOperationsReadinessClosureRoutes);
router.use("/dedicated-homologation/production-operations-readiness/support-runbook-dry-run", fiscalProductionOperationsSupportRunbookRoutes);
router.use("/dedicated-homologation/production-operations-readiness/access-handoff-dry-run", fiscalProductionOperationsAccessHandoffRoutes);
router.use("/dedicated-homologation/production-operations-readiness", fiscalProductionOperationsReadinessRoutes);
router.use("/dedicated-homologation/production-operations-signature-governance/stakeholder-signature-dry-run", fiscalProductionOperationsStakeholderSignatureRoutes);
router.use("/dedicated-homologation/production-operations-signature-governance/committee-deliberation-dry-run", fiscalProductionOperationsSignatureCommitteeRoutes);
router.use("/dedicated-homologation/production-operations-signature-governance/activation-gate-dry-run", fiscalProductionOperationsSignatureActivationGateRoutes);
router.use("/dedicated-homologation/production-operations-signature-governance/closure", fiscalProductionOperationsSignatureGovernanceClosureRoutes);
router.use("/dedicated-homologation/production-operations-signature-governance", fiscalProductionOperationsSignatureGovernanceRoutes);
router.use("/dedicated-homologation/production-physical-execution-firewall/boundary-verification-dry-run", fiscalProductionExecutionBoundaryVerificationRoutes);
router.use("/dedicated-homologation/production-physical-execution-firewall/approval-governance-dry-run", fiscalProductionExecutionFirewallApprovalRoutes);
router.use("/dedicated-homologation/production-physical-execution-firewall/cutover-denial-dry-run", fiscalProductionExecutionCutoverDenialRoutes);
router.use("/dedicated-homologation/production-physical-execution-firewall/closure", fiscalProductionPhysicalExecutionFirewallClosureRoutes);
router.use("/dedicated-homologation/production-physical-execution-firewall", fiscalProductionPhysicalExecutionFirewallRoutes);
router.use("/dedicated-homologation/production-compliance-audit-governance/regulatory-filing-dry-run", fiscalProductionRegulatoryFilingRoutes);
router.use("/dedicated-homologation/production-compliance-audit-governance/finding-remediation-dry-run", fiscalProductionComplianceFindingRoutes);
router.use("/dedicated-homologation/production-compliance-audit-governance/release-gatekeeper-dry-run", fiscalProductionComplianceReleaseGatekeeperRoutes);
router.use("/dedicated-homologation/production-compliance-audit-governance/rollback-shutdown-dry-run", fiscalProductionComplianceRollbackShutdownRoutes);
router.use("/dedicated-homologation/production-compliance-audit-governance/closure", fiscalProductionComplianceAuditClosureRoutes);
router.use("/dedicated-homologation/production-compliance-audit-governance", fiscalProductionComplianceAuditGovernanceRoutes);
router.use("/dedicated-homologation/production-go-live-cutover/rollback-fallback-dry-run", fiscalProductionGoLiveRollbackRoutes);
router.use("/dedicated-homologation/production-go-live-cutover/final-approval-dry-run", fiscalProductionGoLiveFinalApprovalRoutes);
router.use("/dedicated-homologation/production-go-live-cutover/closure", fiscalProductionGoLiveCutoverClosureRoutes);
router.use("/dedicated-homologation/production-post-go-live-stabilization/incident-readiness-dry-run", fiscalProductionPostGoLiveIncidentReadinessRoutes);
router.use("/dedicated-homologation/production-post-go-live-stabilization/observability-health-drift-dry-run", fiscalProductionPostGoLiveObservabilityRoutes);
router.use("/dedicated-homologation/production-post-go-live-stabilization/remediation-war-room-dry-run", fiscalProductionPostGoLiveRemediationRoutes);
router.use("/dedicated-homologation/production-post-go-live-stabilization/closure", fiscalProductionPostGoLiveStabilizationClosureRoutes);
router.use("/dedicated-homologation/production-post-go-live-stabilization", fiscalProductionPostGoLiveStabilizationRoutes);
router.use("/dedicated-homologation/production-traffic-architecture-governance/closure", fiscalProductionTrafficArchitectureClosureRoutes);
router.use("/dedicated-homologation/production-runtime-orchestration-governance/closure", fiscalProductionRuntimeOrchestrationClosureRoutes);
router.use("/dedicated-homologation/production-final-go-live-command-center/command-rollback-dry-run", fiscalProductionFinalGoLiveCommandRollbackRoutes);
router.use("/dedicated-homologation/production-final-state-ledger-governance/final-state-snapshot-dry-run", fiscalProductionFinalStateSnapshotRoutes);
router.use("/dedicated-homologation/production-final-state-ledger-governance/integrity-reconciliation-dry-run", fiscalProductionFinalStateIntegrityRoutes);
router.use("/dedicated-homologation/production-final-state-ledger-governance/disclosure-review-dry-run", fiscalProductionFinalStateDisclosureRoutes);
router.use("/dedicated-homologation/production-final-state-ledger-governance/closure", fiscalProductionFinalStateLedgerClosureRoutes);
router.use("/dedicated-homologation/production-corporate-governance-archive/board-review-dry-run", fiscalProductionCorporateBoardReviewRoutes);
router.use("/dedicated-homologation/production-corporate-governance-archive/closure", fiscalProductionCorporateGovernanceArchiveClosureRoutes);
router.use("/dedicated-homologation/production-corporate-governance-archive", fiscalProductionCorporateGovernanceArchiveRoutes);
router.use("/dedicated-homologation/production-governance-retention-dormancy/access-disclosure-dry-run", fiscalProductionRetentionAccessDisclosureRoutes);
router.use("/dedicated-homologation/production-governance-retention-dormancy/lifecycle-drift-dry-run", fiscalProductionRetentionLifecycleDriftRoutes);
router.use("/dedicated-homologation/production-governance-retention-dormancy/custody-attestation-dry-run", fiscalProductionRetentionCustodyAttestationRoutes);
router.use("/dedicated-homologation/production-governance-retention-dormancy/closure", fiscalProductionGovernanceRetentionDormancyClosureRoutes);
router.use("/dedicated-homologation/production-governance-retention-dormancy", fiscalProductionGovernanceRetentionRoutes);
router.use("/dedicated-homologation/production-system-wide-non-operational-seal/cross-domain-evidence-dry-run", fiscalProductionCrossDomainSealEvidenceRoutes);
router.use("/dedicated-homologation/production-system-wide-non-operational-seal/final-handshake-dry-run", fiscalProductionFinalHandshakeRoutes);
router.use("/dedicated-homologation/production-system-wide-non-operational-seal/handoff-disconnection-dry-run", fiscalProductionSealHandoffDisconnectionRoutes);
router.use("/dedicated-homologation/production-system-wide-non-operational-seal/closure", fiscalProductionSystemWideNonOperationalSealClosureRoutes);
router.use("/dedicated-homologation/production-post-seal-dormant-state-governance", fiscalProductionPostSealDormantStateRoutes);
router.use("/dedicated-homologation/production-post-seal-dormant-state-governance/reentry-denial-dry-run", fiscalProductionReentryAttemptDenialRoutes);
router.use("/dedicated-homologation/production-post-seal-dormant-state-governance/drift-verification-dry-run", fiscalProductionDormantStateDriftVerificationRoutes);
router.use("/dedicated-homologation/production-post-seal-dormant-state-governance/final-review-dry-run", fiscalProductionDormantStateFinalReviewRoutes);
router.use("/dedicated-homologation/production-post-seal-dormant-state-governance/closure", fiscalProductionPostSealDormantStateClosureRoutes);
router.use("/dedicated-homologation/production-system-wide-non-operational-seal", fiscalProductionSystemWideNonOperationalSealRoutes);
router.use("/dedicated-homologation/production-final-state-ledger-governance", fiscalProductionFinalStateLedgerRoutes);
router.use("/dedicated-homologation/production-final-go-live-command-center/closure", fiscalProductionFinalGoLiveCommandCenterClosureRoutes);
router.use("/dedicated-homologation/production-final-go-live-command-center/activation-command-dry-run", fiscalProductionFinalGoLiveActivationCommandRoutes);
router.use("/dedicated-homologation/production-final-go-live-command-center/readiness-decision-dry-run", fiscalProductionFinalGoLiveReadinessRoutes);
router.use("/dedicated-homologation/production-final-go-live-command-center", fiscalProductionFinalGoLiveCommandCenterRoutes);
router.use("/dedicated-homologation/production-runtime-orchestration-governance/external-integration-dry-run", fiscalProductionExternalIntegrationRoutes);
router.use("/dedicated-homologation/production-runtime-orchestration-governance/database-persistence-dry-run", fiscalProductionDatabasePersistenceRoutes);
router.use("/dedicated-homologation/production-runtime-orchestration-governance/scheduler-command-dry-run", fiscalProductionSchedulerCommandRoutes);
router.use("/dedicated-homologation/production-runtime-orchestration-governance/queue-worker-dry-run", fiscalProductionQueueWorkerRoutes);
router.use("/dedicated-homologation/production-runtime-orchestration-governance", fiscalProductionRuntimeOrchestrationRoutes);
router.use("/dedicated-homologation/production-traffic-architecture-governance/route-promotion-dry-run", fiscalProductionRoutePromotionRoutes);
router.use("/dedicated-homologation/production-traffic-architecture-governance/proxy-shadow-dry-run", fiscalProductionProxyShadowRoutes);
router.use("/dedicated-homologation/production-traffic-architecture-governance/load-balancer-dns-dry-run", fiscalProductionLoadBalancerDnsRoutes);
router.use("/dedicated-homologation/production-traffic-architecture-governance", fiscalProductionTrafficArchitectureRoutes);
router.use("/dedicated-homologation/production-go-live-cutover/traffic-routing-dry-run", fiscalProductionTrafficRoutingRoutes);
router.use("/dedicated-homologation/production-go-live-cutover", fiscalProductionGoLiveCutoverRoutes);
router.use("/dedicated-homologation/production-evidence-vault-governance/closure", fiscalProductionEvidenceVaultClosureRoutes);
router.use("/dedicated-homologation/production-evidence-vault-governance/disclosure-export-dry-run", fiscalProductionEvidenceDisclosureRoutes);
router.use("/dedicated-homologation/production-evidence-vault-governance/evidence-intake-dry-run", fiscalProductionEvidenceIntakeRoutes);
router.use("/dedicated-homologation/production-evidence-vault-governance/integrity-custody-dry-run", fiscalProductionEvidenceIntegrityCustodyRoutes);
router.use("/dedicated-homologation/production-evidence-vault-governance", fiscalProductionEvidenceVaultGovernanceRoutes);
router.use("/dedicated-homologation/production-activation-control-plane/closure", fiscalProductionActivationControlPlaneClosureRoutes);
router.use("/dedicated-homologation/production-activation-control-plane/approval-governance-dry-run", fiscalProductionActivationApprovalRoutes);
router.use("/dedicated-homologation/production-activation-control-plane/gate-unlock-dry-run", fiscalProductionActivationGateUnlockRoutes);
router.use("/dedicated-homologation/production-activation-control-plane/canary-ramp-dry-run", fiscalProductionCanaryRampRoutes);
router.use("/dedicated-homologation/production-activation-control-plane", fiscalProductionActivationControlPlaneRoutes);
router.use("/dedicated-homologation/production-baseline-cutover/closure", fiscalProductionBaselineCutoverClosureRoutes);
router.use("/dedicated-homologation/production-baseline-cutover/orchestration-dry-run", fiscalProductionBaselineOrchestrationRoutes);
router.use("/dedicated-homologation/production-baseline-cutover/rollback-reversion-dry-run", fiscalProductionRollbackReversionRoutes);
router.use("/dedicated-homologation/production-baseline-cutover/approval-evidence-dry-run", fiscalProductionBaselineApprovalRoutes);
router.use("/dedicated-homologation/production-baseline-cutover", fiscalProductionBaselineCutoverRoutes);
router.use("/dedicated-homologation/production-operations-transition/traffic-switch-dry-run", fiscalProductionTrafficSwitchRoutes);
router.use("/dedicated-homologation/production-operations-transition/authorization-deliberation-dry-run", fiscalProductionAuthorizationDeliberationRoutes);
router.use("/dedicated-homologation/production-operations-transition/activation-consent-dry-run", fiscalProductionActivationConsentRoutes);
router.use("/dedicated-homologation/production-operations-transition/closure", fiscalProductionOperationsTransitionClosureRoutes);
router.use("/dedicated-homologation/production-operations-transition", fiscalProductionOperationsTransitionRoutes);
router.use("/dedicated-homologation/production-cutover-governance", fiscalProductionCutoverGovernanceRoutes);
router.use("/dedicated-homologation/production-execution-boundary/closure", fiscalProductionExecutionAuthorizationClosureRoutes);
router.use("/dedicated-homologation/production-execution-boundary/final-authorization-dry-run", fiscalProductionFinalAuthorizationRoutes);
router.use("/dedicated-homologation/production-execution-boundary/committee-deliberation-dry-run", fiscalProductionCommitteeDeliberationRoutes);
router.use("/dedicated-homologation/production-execution-boundary/authorization-request-dry-run", fiscalProductionAuthorizationRequestRoutes);
router.use("/dedicated-homologation/production-execution-boundary", fiscalProductionExecutionBoundaryRoutes);
router.use("/dedicated-homologation/production-deployment-isolation/closure", fiscalProductionDeploymentClosureRoutes);
router.use("/dedicated-homologation/production-deployment-isolation/canary-traffic-switch-dry-run", fiscalProductionCanaryTrafficSwitchRoutes);
router.use("/dedicated-homologation/production-deployment-isolation/preflight-dry-run", fiscalProductionPreflightRoutes);
router.use("/dedicated-homologation/production-deployment-isolation/cutover-approval-dry-run", fiscalProductionCutoverApprovalRoutes);
router.use("/dedicated-homologation/production-deployment-isolation/artifact-dry-run", fiscalReleaseArtifactDryRunRoutes);
router.use("/dedicated-homologation/production-deployment-isolation", fiscalProductionDeploymentIsolationRoutes);
router.use("/dedicated-homologation/production-activation/dual-run", fiscalProductionDualRunRoutes);
router.use("/dedicated-homologation/production-activation/rollback-killswitch", fiscalProductionRollbackKillSwitchRoutes);
router.use("/dedicated-homologation/production-activation/release-gateway", fiscalProductionReleaseGatewayRoutes);
router.use("/dedicated-homologation/production-activation/canary-dry-run", fiscalProductionCanaryDryRunRoutes);
router.use("/dedicated-homologation/production-activation", fiscalProductionActivationRoutes);
router.use("/dedicated-homologation/legal-audit-trail/closure", fiscalLegalAuditClosureRoutes);
router.use("/dedicated-homologation/legal-audit-trail/immutability-simulation", fiscalLegalAuditImmutabilityRoutes);
router.use("/dedicated-homologation/legal-audit-trail/event-dry-run", fiscalLegalAuditEventDryRunRoutes);
router.use("/dedicated-homologation/legal-audit-trail/schema-dry-run", fiscalLegalAuditSchemaDryRunRoutes);
router.use("/dedicated-homologation/legal-audit-trail", fiscalLegalAuditTrailRoutes);
router.use("/dedicated-homologation/real-approval-records/mock-signature", fiscalRealApprovalMockSignatureRoutes);
router.use("/dedicated-homologation/real-approval-records/dual-approval-closure", fiscalRealApprovalDualClosureRoutes);
router.use("/dedicated-homologation/real-approval-records/dml-dry-run", fiscalRealApprovalDmlDryRunRoutes);
router.use("/dedicated-homologation/real-approval-records/schema-dry-run", fiscalRealApprovalSchemaDryRunRoutes);
router.use("/dedicated-homologation/real-approval-records/persistence-gate", fiscalRealApprovalPersistenceGateRoutes);
router.use("/dedicated-homologation/real-approval-records/closure", fiscalRealApprovalRecordClosureRoutes);
router.use("/dedicated-homologation/real-approval-records/dry-run", fiscalRealApprovalRecordDryRunRoutes);
router.use("/dedicated-homologation/real-approval-records", fiscalRealApprovalRecordRoutes);
router.use("/dedicated-homologation/real-authorization/dual-approval", fiscalRealDualApprovalRoutes);
router.use("/dedicated-homologation/real-authorization/closure", fiscalRealAuthorizationClosureRoutes);
router.use("/dedicated-homologation/real-authorization", fiscalRealAuthorizationRoutes);
router.use("/dedicated-homologation/real-provisioning/closure", fiscalRealProvisioningClosureRoutes);
router.use("/dedicated-homologation/real-provisioning/change-window", fiscalRealChangeWindowRoutes);
router.use("/dedicated-homologation/real-provisioning/security", fiscalRealProvisioningSecurityRoutes);
router.use("/dedicated-homologation/real-provisioning", fiscalRealProvisioningRoutes);
router.use("/dedicated-homologation", fiscalDedicatedHomologationRoutes);

/**
 * Rotas fiscais modulares de leitura em modo paralelo.
 * Não substituem rotas fiscais legadas nesta Sprint.
 * Estão montadas sob o prefixo /api/fiscal-v2 no server.ts.
 */

// Fiscal Documents
router.get("/documents", (req, res) => fiscalDocumentController.listDocuments(req, res));
router.get("/documents/:id", (req, res) => fiscalDocumentController.getDocumentById(req, res));

// NFe
router.get("/nfe", (req, res) => nfeController.listNfe(req, res));
router.get("/nfe/:id", (req, res) => nfeController.getNfeById(req, res));

// NFCe
router.get("/nfce", (req, res) => nfceController.listNfce(req, res));
router.get("/nfce/:id", (req, res) => nfceController.getNfceById(req, res));

// Danfe
router.get("/danfe", (req, res) => danfeController.listDanfe(req, res));
router.get("/danfe/:id", (req, res) => danfeController.getDanfeById(req, res));
router.get("/danfe/by-nfe/:nfeId", (req, res) => danfeController.getDanfeByNfeId(req, res));

// Sefaz Protocols
router.get("/sefaz/protocols", (req, res) => sefazProtocolController.listProtocols(req, res));
router.get("/sefaz/protocols/by-document/:documentId", (req, res) => sefazProtocolController.getProtocolsByDocumentId(req, res));

/**
 * Rotas POST desta Sprint são exclusivamente dry-run. Não executam persistência, transmissão, assinatura ou geração de documentos.
 */
router.post("/dry-run/documents", (req, res) => fiscalDocumentController.dryRunCreateDocument(req, res));
router.post("/dry-run/nfe", (req, res) => nfeController.dryRunCreateNfe(req, res));
router.post("/dry-run/nfe/:id/status", (req, res) => nfeController.dryRunUpdateNfeStatus(req, res));
router.post("/dry-run/nfce", (req, res) => nfceController.dryRunCreateNfce(req, res));
router.post("/dry-run/nfce/:id/cancel", (req, res) => nfceController.dryRunCancelNfce(req, res));
router.post("/dry-run/danfe", (req, res) => danfeController.dryRunSaveDanfe(req, res));
router.post("/dry-run/sefaz/protocols", (req, res) => sefazProtocolController.dryRunSaveProtocol(req, res));

export { router as fiscalRoutes };
