import {
  FiscalProductionTrafficArchitectureInput,
  FiscalProductionTrafficArchitectureResult,
  FiscalProductionTrafficArchitectureStatus
} from './FiscalProductionTrafficArchitectureTypes';
import { FiscalProductionTrafficArchitectureValidator } from './FiscalProductionTrafficArchitectureValidator';
import { FiscalProductionTrafficArchitectureEvaluationService } from './FiscalProductionTrafficArchitectureEvaluationService';

export class FiscalProductionTrafficArchitectureDecisionService {
  public static simulateDecision(input: FiscalProductionTrafficArchitectureInput): FiscalProductionTrafficArchitectureResult {
    const errors = FiscalProductionTrafficArchitectureValidator.validate(input);
    const warnings = FiscalProductionTrafficArchitectureEvaluationService.evaluate(input);

    const isBlocked = errors.length > 0;

    return {
      success: !isBlocked,
      status: isBlocked ? FiscalProductionTrafficArchitectureStatus.BLOCKED_FOR_REAL_TRAFFIC_MUTATION : FiscalProductionTrafficArchitectureStatus.PRODUCTION_TRAFFIC_ARCHITECTURE_BLUEPRINT_READY,
      validationExecuted: true,
      evaluationExecuted: true,
      decisionSimulated: true,
      trafficArchitectureGovernanceBlueprintGenerated: true,
      hardNoRoutingExecutionContractGenerated: true,
      trafficTopologyInventoryGenerated: true,
      legacyRoutePreservationPlanGenerated: true,
      v2RouteLockedPlanGenerated: true,
      loadBalancerNoChangePlanGenerated: true,
      dnsNoChangePlanGenerated: true,
      proxyMiddlewareNoInstallPlanGenerated: true,
      shadowTrafficNoActivationPlanGenerated: true,
      trafficMutationBlockMatrixGenerated: true,
      routingExecutionBoundaryMatrixGenerated: true,
      dependencyMatrixGenerated: true,
      blockersGenerated: true,
      risksGenerated: true,
      go: false,
      noGo: true,
      blockers: errors,
      warnings,
      productionTrafficArchitectureBlueprintOnly: true,
      hardNoRoutingExecutionContractOnly: true,
      legacyRoutePreservationOnly: true,
      realTrafficChanged: false,
      productionV2Activated: false,
      routeToV2: false,
      routeToLegacy: true,
      realLoadBalancerSwitched: false,
      realDnsChanged: false,
      realProxyInstalled: false,
      realMiddlewareInstalled: false,
      realTapInstalled: false,
      realMirrorEnabled: false,
      realSnifferEnabled: false,
      realShadowTrafficEnabled: false,
      realRequestCaptured: false,
      realResponseCaptured: false,
      realPayloadCaptured: false,
      realLegacyHandlerCalled: false,
      realV2HandlerCalled: false,
      realExecutionGateUnlocked: false,
      realAuthorizationGranted: false,
      realAuthorizationTokenIssued: false,
      realCutoverExecuted: false,
      realGoLiveConcluded: false,
      realReleaseExecuted: false,
      realRolloutExecuted: false,
      realCanaryActivated: false,
      realRollbackExecuted: false,
      realAbortExecuted: false,
      realFallbackExecuted: false,
      realShutdownExecuted: false,
      realRuntimeStarted: false,
      realQueueStarted: false,
      realJobEnqueued: false,
      realWorkerDispatched: false,
      realSchedulerCreated: false,
      realCronCreated: false,
      realShellCommandExecuted: false,
      realDatabaseConnected: false,
      dmlExecuted: false,
      ddlExecuted: false,
      realSefazCalled: false,
      realPayloadRead: false,
      realXmlRead: false,
      realPdfRead: false,
      realPfxRead: false,
      realCertificateRead: false,
      certificatePasswordRead: false,
      realSecretRead: false,
      privateKeyRead: false,
      tokenRead: false,
      realCryptoUsed: false,
      realHashCalculated: false,
      xmlSigned: false,
      pdfGenerated: false,
      fileSystemWritten: false,
      externalStorageUploaded: false,
      readOnly: true,
      governanceOnly: true,
      simulationOnly: true,
      activationBlocked: true,
      payloadIncluded: false,
      sensitiveDataIncluded: false,
      approvedForTrafficArchitectureDocumentation: true,
      approvedForRoutingReadinessModeling: true,
      approvedForRealTrafficMutation: false,
      approvedForProductionV2: false,
      approvedForRouteToV2: false
    };
  }
}
