export class FiscalRealSecurityReviewChecklist {
  public static getChecklist() {
    return [
      { id: 'C-RS-01', description: 'IaC dry-run 12.2 criado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'Dry-run API available.' },
      { id: 'C-RS-02', description: 'Resource catalog criado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'Catalog static present.' },
      { id: 'C-RS-03', description: 'State backend plan criado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'Backend plan available.' },
      { id: 'C-RS-04', description: 'Variable plan criado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'Variable plan available.' },
      { id: 'C-RS-05', description: 'Secret vault dry-run contract criado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'Contract established.' },
      { id: 'C-RS-06', description: 'Validadores de secrets criados.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'Secret validation present.' },
      { id: 'C-RS-07', description: 'Validadores de certificado criados.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'Cert validator logic created.' },
      { id: 'C-RS-08', description: 'Validadores de access policy criados.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'Access policy validator.' },
      { id: 'C-RS-09', description: 'Validadores de rotation policy criados.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'Rotation policy validator.' },
      { id: 'C-RS-10', description: 'Validadores de audit policy criados.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'Audit policy validator.' },
      { id: 'C-RS-11', description: 'Nenhum terraform apply executado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'iacApplied false.' },
      { id: 'C-RS-12', description: 'Nenhum pulumi up executado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'pulumiApplied false.' },
      { id: 'C-RS-13', description: 'Nenhum cloud deploy executado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'cloudFormationDeployed false.' },
      { id: 'C-RS-14', description: 'Nenhum recurso real criado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'realResourceCreated false.' },
      { id: 'C-RS-15', description: 'Nenhum banco real criado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'databaseProvisioned false.' },
      { id: 'C-RS-16', description: 'Nenhum banco real conectado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'realDatabaseConnected false.' },
      { id: 'C-RS-17', description: 'Nenhum vault real criado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'vaultProvisioned false.' },
      { id: 'C-RS-18', description: 'Nenhum secret real escrito.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'secretWritten false.' },
      { id: 'C-RS-19', description: 'Nenhum secret real carregado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'secretLoaded false.' },
      { id: 'C-RS-20', description: 'Nenhum certificado real carregado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'certificateLoaded false.' },
      { id: 'C-RS-21', description: 'Nenhum PFX real lido.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'realPfxRead false.' },
      { id: 'C-RS-22', description: 'Nenhuma senha de certificado lida.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'certificatePasswordRead false.' },
      { id: 'C-RS-23', description: 'Nenhuma SEFAZ real chamada.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'realSefazCalled false.' },
      { id: 'C-RS-24', description: 'Nenhum XML real assinado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'realXmlSigned false.' },
      { id: 'C-RS-25', description: 'Nenhum PDF real gerado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'realPdfGenerated false.' },
      { id: 'C-RS-26', description: 'Nenhuma Produção V2 ativada.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'productionV2Activated false.' },
      { id: 'C-RS-27', description: 'Nenhum tráfego real alterado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'trafficChanged false.' },
      { id: 'C-RS-28', description: 'Nenhum endpoint real chamado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'endpointCalled false.' },
      { id: 'C-RS-29', description: 'Nenhum handler legado chamado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'legacy flags untouched.' },
      { id: 'C-RS-30', description: 'Nenhum handler V2 operacional chamado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'v2 flags false.' },
      { id: 'C-RS-31', description: 'Nenhum worker criado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'workersCreated false.' },
      { id: 'C-RS-32', description: 'Nenhum scheduler/cron/setInterval/queue.process criado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'schedulersCreated false.' },
      { id: 'C-RS-33', description: 'Nenhum DML fiscal real ocorreu.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'No database inserts.' },
      { id: 'C-RS-34', description: 'Payload bruto não foi exposto.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'payloadIncluded false.' },
      { id: 'C-RS-35', description: 'Dado sensível não foi exposto.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'sensitiveDataIncluded false.' },
      { id: 'C-RS-36', description: 'Boot Policy permanece preservada.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'Tests pass.' },
      { id: 'C-RS-37', description: 'RLS permanece preservado.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'RLS untouched.' },
      { id: 'C-RS-38', description: 'Rotas legadas permanecem preservadas.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'Legacy routes exist.' },
      { id: 'C-RS-39', description: 'Respostas legadas permanecem preservadas.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'Tests pass.' },
      { id: 'C-RS-40', description: 'Scripts temporários foram removidos ou justificados.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'No root scripts.' },
      { id: 'C-RS-41', description: 'Revisão de segurança pode ser aprovada documentalmente.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'approvedForSecurityReviewClosure true.' },
      { id: 'C-RS-42', description: 'Aprovação real permanece bloqueada.', passed: true, blockerForSecurityReviewClosure: false, blockerForRealApproval: true, evidence: 'approvedForIacApply false.' }
    ];
  }
}
