import {
  FiscalProductionRetentionAccessDisclosureInput,
  FiscalProductionRetentionAccessDisclosureResult,
  FiscalProductionRetentionAccessDisclosureStatus
} from './FiscalProductionRetentionAccessDisclosureTypes';
import { FiscalProductionRetentionAccessDisclosureValidator } from './FiscalProductionRetentionAccessDisclosureValidator';
import { FiscalProductionRetentionAccessDisclosureEvaluationService } from './FiscalProductionRetentionAccessDisclosureEvaluationService';

export class FiscalProductionRetentionAccessDisclosureDecisionService {
  public static simulateDecision(input: FiscalProductionRetentionAccessDisclosureInput): FiscalProductionRetentionAccessDisclosureResult {
    const errors = FiscalProductionRetentionAccessDisclosureValidator.validate(input);
    const warnings = FiscalProductionRetentionAccessDisclosureEvaluationService.evaluate(input);
    const isBlocked = errors.length > 0;

    return {
      success: !isBlocked,
      status: isBlocked ? FiscalProductionRetentionAccessDisclosureStatus.BLOCKED_FOR_REAL_ACCESS_OR_EXPORT : FiscalProductionRetentionAccessDisclosureStatus.PRODUCTION_RETENTION_ACCESS_DISCLOSURE_REVIEW_READY,
      validationExecuted: true,
      evaluationExecuted: true,
      decisionSimulated: true,
      retentionDormancyAccessReviewBlueprintGenerated: true,
      dormantRecordAccessNoGrantMatrixGenerated: true,
      retrievalSuppressionNoReadPlanGenerated: true,
      disclosureEligibilityNoApproveMatrixGenerated: true,
      exportPackageNoCreatePlanGenerated: true,
      downloadLinkNoIssueMatrixGenerated: true,
      presignedUrlNoGeneratePlanGenerated: true,
      recipientDisclosureNoNotifyMatrixGenerated: true,
      redactionNoReadNoApplyPlanGenerated: true,
      accessAuditNoPersistencePlanGenerated: true,
      retentionDisclosureNoLegalEffectNoticeGenerated: true,
      noRealAccessGrantEvidenceGenerated: true,
      noRealRetrievalEvidenceGenerated: true,
      noRealDisclosureExportEvidenceGenerated: true,
      dependencyMatrixGenerated: true,
      blockersGenerated: true,
      risksGenerated: true,
      go: false,
      noGo: true,
      blockers: errors,
      warnings,
      productionRetentionDormancyAccessReviewOnly: true,
      retrievalSuppressionOnly: true,
      noDisclosureOnly: true,
      noExportOnly: true,
      noRealAccessOnly: true,
      noRealRetrievalOnly: true,
      noRealDownloadOnly: true,
      noRealDisclosureOnly: true,
      noRealPackageOnly: true,
      noRealRecordOnly: true,
      noRealFileOnly: true,
      noPersistenceOnly: true,
      noPayloadReadOnly: true,
      noDatabaseReadOnly: true,
      noExternalSubmissionOnly: true,
      realAccessGranted: false,
      realRecordRetrieved: false,
      realArchiveRead: false,
      realRetentionRecordRead: false,
      realCustodyRecordRead: false,
      realDisclosureRecordRead: false,
      realDisclosureApproved: false,
      realExportPackageCreated: false,
      realDownloadLinkGenerated: false,
      realPresignedUrlGenerated: false,
      realDisclosurePackageSent: false,
      realRecipientNotified: false,
      realStakeholderNotified: false,
      realDirectorNotified: false,
      realAuditorNotified: false,
      realRegulatorNotified: false,
      realRedactionApplied: false,
      realAccessAuditPersisted: false,
      realDisclosureRecordPersisted: false,
      realExportRecordPersisted: false,
      realPdfGenerated: false,
      realZipGenerated: false,
      realJsonGenerated: false,
      realCsvGenerated: false,
      realHashGenerated: false,
      realSignatureGenerated: false,
      realProofCreated: false,
      realCryptographicProofCreated: false,
      realPayloadRead: false,
      realXmlRead: false,
      realPdfRead: false,
      realTenantDataRead: false,
      realFiscalDocumentRead: false,
      realFilesystemWritten: false,
      realStorageUploaded: false,
      realDatabaseWritten: false,
      realGoLiveApproved: false,
      realGoLiveExecuted: false,
      realActivationCommandExecuted: false,
      realActivationAuthorityGranted: false,
      realExecutionGateUnlocked: false,
      realAuthorizationTokenIssued: false,
      productionV2Activated: false,
      routeToV2: false,
      routeToLegacy: true,
      realTrafficChanged: false,
      realRuntimeStarted: false,
      realQueueStarted: false,
      realJobEnqueued: false,
      realWorkerDispatched: false,
      realDatabaseConnected: false,
      dmlExecuted: false,
      ddlExecuted: false,
      realMigrationRun: false,
      realSefazCalled: false,
      realExternalApiCalled: false,
      realWebhookSent: false,
      realSlackSent: false,
      realWhatsappSent: false,
      realEmailSent: false,
      realPagerSent: false,
      tokenRead: false,
      realSecretRead: false,
      apiKeyRead: false,
      clientSecretRead: false,
      authorizationHeaderRead: false,
      databaseUrlRead: false,
      connectionStringRead: false,
      realCertificateRead: false,
      realPfxRead: false,
      certificatePasswordRead: false,
      privateKeyRead: false,
      realCryptoUsed: false,
      xmlSigned: false,
      readOnly: true,
      governanceOnly: true,
      simulationOnly: true,
      activationBlocked: true,
      payloadIncluded: false,
      sensitiveDataIncluded: false,
      approvedForVirtualAccessReviewDocumentation: true,
      approvedForRetrievalSuppressionDocumentation: true,
      approvedForNoDisclosureDocumentation: true,
      approvedForRealAccessGrant: false,
      approvedForRealRetrieval: false,
      approvedForRealDisclosure: false,
      approvedForRealExport: false,
      approvedForRealDownload: false,
      approvedForRealRecordPersistence: false,
      approvedForRealGoLiveExecution: false,
      approvedForProductionV2: false,
      approvedForRouteToV2: false,
      lintGlobalKnownIssueAcknowledged: true,
      ts2308KnownIssueAcknowledged: true,
      namespaceOverlapIntroducedByModule44_4: false
    };
  }
}
