import {
  FiscalProductionGoLiveFinalApprovalInput,
  FiscalProductionGoLiveFinalApprovalResult,
  FiscalProductionGoLiveFinalApprovalStatus
} from './FiscalProductionGoLiveFinalApprovalTypes';
import { FiscalProductionGoLiveFinalApprovalValidator } from './FiscalProductionGoLiveFinalApprovalValidator';
import { FiscalProductionGoLiveFinalApprovalEvaluationService } from './FiscalProductionGoLiveFinalApprovalEvaluationService';

export class FiscalProductionGoLiveFinalApprovalDecisionService {
  public static simulateDecision(input: FiscalProductionGoLiveFinalApprovalInput): FiscalProductionGoLiveFinalApprovalResult {
    const errors = FiscalProductionGoLiveFinalApprovalValidator.validate(input);
    const warnings = FiscalProductionGoLiveFinalApprovalEvaluationService.evaluate(input);

    const isBlocked = errors.length > 0;

    return {
      success: !isBlocked,
      status: isBlocked ? FiscalProductionGoLiveFinalApprovalStatus.BLOCKED_FOR_REAL_APPROVAL_OR_ACTIVATION : FiscalProductionGoLiveFinalApprovalStatus.PRODUCTION_GO_LIVE_FINAL_APPROVAL_NO_OP_READY,
      validationExecuted: true,
      evaluationExecuted: true,
      decisionSimulated: true,
      finalApprovalPackageGenerated: true,
      executiveSignOffSimulationMatrixGenerated: true,
      finalReadinessEvidenceReviewMatrixGenerated: true,
      noActivationDecisionMatrixGenerated: true,
      authorizationNoGrantPlanGenerated: true,
      goLiveApprovalNoOpPlanGenerated: true,
      cutoverDecisionNoExecuteMatrixGenerated: true,
      rollbackFallbackEvidenceReviewMatrixGenerated: true,
      noRealApprovalEvidenceGenerated: true,
      noRealAuthorizationEvidenceGenerated: true,
      dependencyMatrixGenerated: true,
      blockersGenerated: true,
      risksGenerated: true,
      go: false,
      noGo: true,
      blockers: errors,
      warnings,
      productionGoLiveFinalApprovalNoOpOnly: true,
      executiveSignOffSimulationOnly: true,
      noActivationDecisionOnly: true,
      realGoLiveApproved: false,
      realCutoverApproved: false,
      realExecutiveSignOffConcluded: false,
      realSignatureCollected: false,
      realAuthorizationGranted: false,
      realExecutionGateUnlocked: false,
      realAuthorizationTokenIssued: false,
      productionV2Activated: false,
      routeToV2: false,
      routeToLegacy: true,
      trafficChanged: false,
      realGoLiveExecuted: false,
      realCutoverExecuted: false,
      realRollbackExecuted: false,
      realAbortExecuted: false,
      realFallbackExecuted: false,
      realReleaseExecuted: false,
      realRolloutExecuted: false,
      realCanaryActivated: false,
      realShutdownExecuted: false,
      realLoadBalancerSwitched: false,
      realDnsChanged: false,
      realProxyInstalled: false,
      realMiddlewareInstalled: false,
      realTapInstalled: false,
      realShadowTrafficEnabled: false,
      realRequestCaptured: false,
      realResponseCaptured: false,
      realPayloadCaptured: false,
      realLegacyHandlerCalled: false,
      realV2HandlerCalled: false,
      realRuntimeStarted: false,
      realQueueStarted: false,
      realJobEnqueued: false,
      realWorkerDispatched: false,
      realShellCommandExecuted: false,
      realDatabaseConnected: false,
      dmlExecuted: false,
      ddlExecuted: false,
      realSefazCalled: false,
      realPayloadRead: false,
      realXmlRead: false,
      realPdfRead: false,
      realPfxRead: false,
      realCertificateRead: false,
      certificatePasswordRead: false,
      realSecretRead: false,
      privateKeyRead: false,
      tokenRead: false,
      realCryptoUsed: false,
      realHashCalculated: false,
      xmlSigned: false,
      pdfGenerated: false,
      fileSystemWritten: false,
      externalStorageUploaded: false,
      realIncidentCreated: false,
      realTicketCreated: false,
      realRemediationExecuted: false,
      webhookSent: false,
      slackSent: false,
      whatsappSent: false,
      emailSent: false,
      pagerSent: false,
      pagerDutySent: false,
      opsgenieSent: false,
      realStakeholderNotified: false,
      realApproverNotified: false,
      realCustomerNotified: false,
      realOperatorNotified: false,
      readOnly: true,
      governanceOnly: true,
      simulationOnly: true,
      activationBlocked: true,
      payloadIncluded: false,
      sensitiveDataIncluded: false,
      approvedForFinalApprovalNoOp: true,
      approvedForExecutiveSignOffSimulation: true,
      approvedForNoActivationDecision: true,
      approvedForRealGoLiveApproval: false,
      approvedForRealCutoverApproval: false,
      approvedForRealAuthorization: false,
      approvedForProductionV2: false,
      approvedForRouteToV2: false
    };
  }
}
