import {
  FiscalProductionExternalIntegrationInput,
  FiscalProductionExternalIntegrationResult,
  FiscalProductionExternalIntegrationStatus
} from './FiscalProductionExternalIntegrationTypes';
import { FiscalProductionExternalIntegrationValidator } from './FiscalProductionExternalIntegrationValidator';
import { FiscalProductionExternalIntegrationEvaluationService } from './FiscalProductionExternalIntegrationEvaluationService';

export class FiscalProductionExternalIntegrationDecisionService {
  public static simulateDecision(input: FiscalProductionExternalIntegrationInput): FiscalProductionExternalIntegrationResult {
    const errors = FiscalProductionExternalIntegrationValidator.validate(input);
    const warnings = FiscalProductionExternalIntegrationEvaluationService.evaluate(input);
    
    const isBlocked = errors.length > 0;

    return {
      success: !isBlocked,
      status: isBlocked ? FiscalProductionExternalIntegrationStatus.BLOCKED_FOR_REAL_EXTERNAL_INTEGRATION : FiscalProductionExternalIntegrationStatus.PRODUCTION_EXTERNAL_INTEGRATION_DRY_RUN_READY,
      validationExecuted: true,
      evaluationExecuted: true,
      decisionSimulated: true,
      externalIntegrationNoCallBlueprintGenerated: true,
      sefazAdapterNoCallPlanGenerated: true,
      authorizationTokenNoIssueMatrixGenerated: true,
      externalWebhookNoSendPlanGenerated: true,
      notificationProviderNoSendMatrixGenerated: true,
      externalCallbackNoRegisterPlanGenerated: true,
      httpAdapterNoBindMatrixGenerated: true,
      externalCredentialNoReadPlanGenerated: true,
      apiKeySecretNoReadMatrixGenerated: true,
      certificatePfxNoReadPlanGenerated: true,
      fiscalPayloadNoReadMatrixGenerated: true,
      externalNoRealCallEvidenceGenerated: true,
      authorizationNoRealTokenEvidenceGenerated: true,
      dependencyMatrixGenerated: true,
      blockersGenerated: true,
      risksGenerated: true,
      go: false,
      noGo: true,
      blockers: errors,
      warnings,
      productionExternalIntegrationDryRunOnly: true,
      externalIntegrationNoCallOnly: true,
      sefazAdapterNoCallOnly: true,
      authorizationTokenNoIssueOnly: true,
      webhookNotificationNoSendOnly: true,
      externalCallbackNoRegisterOnly: true,
      adapterCredentialNoReadOnly: true,
      realExternalApiCalled: false,
      realSefazCalled: false,
      realHttpAdapterBound: false,
      realCallbackRegistered: false,
      realWebhookSent: false,
      realSlackSent: false,
      realWhatsappSent: false,
      realEmailSent: false,
      realPagerSent: false,
      realAuthorizationTokenIssued: false,
      realAuthorizationGranted: false,
      realExecutionGateUnlocked: false,
      tokenRead: false,
      realSecretRead: false,
      apiKeyRead: false,
      clientSecretRead: false,
      authorizationHeaderRead: false,
      realCertificateRead: false,
      realPfxRead: false,
      certificatePasswordRead: false,
      privateKeyRead: false,
      realCryptoUsed: false,
      xmlSigned: false,
      pdfGenerated: false,
      realPayloadRead: false,
      realXmlRead: false,
      realPdfRead: false,
      realTenantDataRead: false,
      realFiscalDocumentRead: false,
      realDatabaseConnected: false,
      dmlExecuted: false,
      ddlExecuted: false,
      realRuntimeStarted: false,
      realQueueStarted: false,
      realJobEnqueued: false,
      realWorkerDispatched: false,
      realSchedulerCreated: false,
      realCronCreated: false,
      realShellCommandExecuted: false,
      realCommandRunnerExecuted: false,
      productionV2Activated: false,
      routeToV2: false,
      routeToLegacy: true,
      realTrafficChanged: false,
      realLoadBalancerSwitched: false,
      realDnsChanged: false,
      realProxyInstalled: false,
      realMiddlewareInstalled: false,
      realTapInstalled: false,
      realMirrorEnabled: false,
      realSnifferEnabled: false,
      realShadowTrafficEnabled: false,
      realRequestCaptured: false,
      realResponseCaptured: false,
      realPayloadCaptured: false,
      readOnly: true,
      governanceOnly: true,
      simulationOnly: true,
      activationBlocked: true,
      payloadIncluded: false,
      sensitiveDataIncluded: false,
      approvedForExternalIntegrationDocumentation: true,
      approvedForSefazBoundaryModeling: true,
      approvedForAuthorizationTokenModeling: true,
      approvedForRealExternalCall: false,
      approvedForRealSefazCall: false,
      approvedForRealTokenIssue: false,
      approvedForProductionV2: false,
      approvedForRouteToV2: false
    };
  }
}
