export class FiscalRealPreExecutionChecklist {
  public static getChecklist() {
    return [
      { id: 'C-CW-01', description: 'IaC dry-run 12.2 criado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'Dry-run API available.' },
      { id: 'C-CW-02', description: 'Security Review 12.3 criado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'Security API available.' },
      { id: 'C-CW-03', description: 'Approval Matrix criada.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'Matrix available.' },
      { id: 'C-CW-04', description: 'Segregation of Duties criada.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'SoD Matrix available.' },
      { id: 'C-CW-05', description: 'Change Window planejada.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'Calendar populated.' },
      { id: 'C-CW-06', description: 'Rollback operacional planejado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'Rollback controls present.' },
      { id: 'C-CW-07', description: 'Communication plan planejado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'Plan available.' },
      { id: 'C-CW-08', description: 'Nenhuma janela real aberta.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'realWindowOpened false.' },
      { id: 'C-CW-09', description: 'Nenhuma execução real iniciada.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'executionStarted false.' },
      { id: 'C-CW-10', description: 'Nenhum terraform apply executado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'iacApplied false.' },
      { id: 'C-CW-11', description: 'Nenhum pulumi up executado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'pulumiApplied false.' },
      { id: 'C-CW-12', description: 'Nenhum cloud deploy executado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'cloudFormationDeployed false.' },
      { id: 'C-CW-13', description: 'Nenhum recurso real criado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'realResourceCreated false.' },
      { id: 'C-CW-14', description: 'Nenhum banco real criado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'databaseProvisioned false.' },
      { id: 'C-CW-15', description: 'Nenhum banco real conectado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'realDatabaseConnected false.' },
      { id: 'C-CW-16', description: 'Nenhum vault real criado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'vaultProvisioned false.' },
      { id: 'C-CW-17', description: 'Nenhum secret real escrito.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'secretWritten false.' },
      { id: 'C-CW-18', description: 'Nenhum certificado real carregado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'certificateLoaded false.' },
      { id: 'C-CW-19', description: 'Nenhum PFX real lido.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'realPfxRead false.' },
      { id: 'C-CW-20', description: 'Nenhuma senha de certificado lida.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'certificatePasswordRead false.' },
      { id: 'C-CW-21', description: 'Nenhuma SEFAZ real chamada.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'realSefazCalled false.' },
      { id: 'C-CW-22', description: 'Nenhum XML real assinado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'realXmlSigned false.' },
      { id: 'C-CW-23', description: 'Nenhum PDF real gerado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'realPdfGenerated false.' },
      { id: 'C-CW-24', description: 'Nenhuma Produção V2 ativada.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'productionV2Activated false.' },
      { id: 'C-CW-25', description: 'Nenhum tráfego real alterado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'trafficChanged false.' },
      { id: 'C-CW-26', description: 'Nenhum endpoint real chamado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'endpointCalled false.' },
      { id: 'C-CW-27', description: 'Nenhum handler legado chamado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'legacy flags untouched.' },
      { id: 'C-CW-28', description: 'Nenhum handler V2 operacional chamado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'v2 flags false.' },
      { id: 'C-CW-29', description: 'Nenhum worker criado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'workersCreated false.' },
      { id: 'C-CW-30', description: 'Nenhum scheduler/cron/setInterval/queue.process criado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'schedulersCreated false.' },
      { id: 'C-CW-31', description: 'Nenhum DML fiscal real ocorreu.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'No database inserts.' },
      { id: 'C-CW-32', description: 'Payload bruto não foi exposto.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'payloadIncluded false.' },
      { id: 'C-CW-33', description: 'Dado sensível não foi exposto.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'sensitiveDataIncluded false.' },
      { id: 'C-CW-34', description: 'Boot Policy permanece preservada.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'Tests pass.' },
      { id: 'C-CW-35', description: 'RLS permanece preservado.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'RLS untouched.' },
      { id: 'C-CW-36', description: 'Rotas legadas permanecem preservadas.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'Legacy routes exist.' },
      { id: 'C-CW-37', description: 'Respostas legadas permanecem preservadas.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'Tests pass.' },
      { id: 'C-CW-38', description: 'Scripts temporários foram removidos ou justificados.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'No root scripts.' },
      { id: 'C-CW-39', description: 'Planejamento de janela pode ser aprovado documentalmente.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'approvedForChangeWindowClosure true.' },
      { id: 'C-CW-40', description: 'Execução real permanece bloqueada.', passed: true, blockerForChangeWindowClosure: false, blockerForRealExecution: true, evidence: 'approvedForExecutionStart false.' }
    ];
  }
}
