import { FiscalProductionOperationsSignatureGovernanceStatus, FiscalProductionOperationsSignatureGovernanceResult } from './FiscalProductionOperationsSignatureGovernanceTypes';
import { FiscalProductionOperationsSignatureGovernanceBlockerRegister } from './FiscalProductionOperationsSignatureGovernanceBlockerRegister';
import { FiscalProductionOperationsSignatureGovernanceRiskRegister } from './FiscalProductionOperationsSignatureGovernanceRiskRegister';

export class FiscalProductionOperationsSignatureGovernanceDecisionService {
  public static simulateDecision(): FiscalProductionOperationsSignatureGovernanceResult {
    return {
      success: true,
      status: FiscalProductionOperationsSignatureGovernanceStatus.PRODUCTION_OPERATIONS_SIGNATURE_GOVERNANCE_BLUEPRINT_READY,
      validationExecuted: true,
      evaluationExecuted: true,
      decisionSimulated: true,
      signatureGovernanceBlueprintGenerated: true,
      nonExecutableActivationConsentContractGenerated: true,
      authorizedSignerMatrixGenerated: true,
      twoPersonSignatureSimulationGenerated: true,
      signatureSoDMatrixGenerated: true,
      nonCryptographicSignatureEnvelopeGenerated: true,
      signatureEvidenceNoPersistencePlanGenerated: true,
      noRealSignatureEvidenceGenerated: true,
      noGateUnlockEvidenceGenerated: true,
      dependencyMatrixGenerated: true,
      blockersGenerated: true,
      risksGenerated: true,
      go: false,
      noGo: true,
      blockers: FiscalProductionOperationsSignatureGovernanceBlockerRegister.getBlockers(),
      warnings: FiscalProductionOperationsSignatureGovernanceRiskRegister.getRisks(),
      productionOperationsSignatureGovernanceBlueprintOnly: true,
      nonExecutableActivationConsentOnly: true,
      nonCryptographicSignatureEnvelopeOnly: true,
      realSignatureGranted: false,
      realCryptographicSignatureCollected: false,
      realConsentPersisted: false,
      realSignatureRecordPersisted: false,
      realAuthorizationGranted: false,
      realExecutionGateUnlocked: false,
      realOperationsTransitionExecuted: false,
      realOperationsActivated: false,
      realOperationsHandoffCompleted: false,
      productionV2Activated: false,
      routeToV2: false,
      routeToLegacy: true,
      trafficChanged: false,
      realCertificateRead: false,
      realPfxRead: false,
      certificatePasswordRead: false,
      realSecretRead: false,
      realCryptoUsed: false,
      xmlSigned: false,
      pdfGenerated: false,
      webhookSent: false,
      slackSent: false,
      whatsappSent: false,
      emailSent: false,
      pagerSent: false,
      realDatabaseConnected: false,
      dmlExecuted: false,
      ddlExecuted: false,
      realSefazCalled: false,
      runtimeExecutionStarted: false,
      commandQueueStarted: false,
      realJobEnqueued: false,
      realWorkerDispatched: false,
      workersCreated: false,
      schedulersCreated: false,
      cronCreated: false,
      commandRunnerExecuted: false,
      shellCommandExecuted: false,
      readOnly: true,
      governanceOnly: true,
      simulationOnly: true,
      activationBlocked: true,
      payloadIncluded: false,
      sensitiveDataIncluded: false,
      approvedForSignatureGovernanceBlueprint: true,
      approvedForNonExecutableActivationConsent: true,
      approvedForNonCryptographicSignatureEnvelope: true,
      approvedForRealSignature: false,
      approvedForRealGateUnlock: false,
      approvedForRealAuthorization: false,
      approvedForRealOperationsActivation: false,
      approvedForProductionV2: false,
      approvedForRouteToV2: false,
      approvedForRealDatabaseConnection: false,
      approvedForRealSefazCall: false,
      approvedForRealSigning: false
    };
  }
}
