import { SmartCardItem } from './types';

// Dados exclusivamente fictícios para demonstrar o fluxo manual do MVP.
export const MOCK_SMART_CARDS: SmartCardItem[] = [
  {
    id: 'mock-alert-01',
    kind: 'ai-alert',
    title: 'Pagamento cartão crédito — R$ 30,00',
    description: 'Possível recebimento duplicado no balcão. Confira manualmente antes de organizar.',
    amount: 30,
    timeLabel: 'há 8 min',
    status: 'pending',
    archived: false,
    linked: false,
    hasPreInvoice: false,
    tags: ['Sugestão da IA', 'Conferir manualmente'],
  },
  {
    id: 'mock-pending-01',
    kind: 'pending',
    title: 'Despesa fornecedor — R$ 120,00',
    description: 'Comprovante de fornecedor sem categoria definida para revisar depois.',
    amount: 120,
    timeLabel: 'há 22 min',
    status: 'pending',
    archived: false,
    linked: false,
    hasPreInvoice: false,
    tags: ['Falta informação'],
  },
  {
    id: 'mock-capture-01',
    kind: 'capture',
    title: 'Foto de comprovante Pix — R$ 45,00',
    description: 'Imagem registrada rapidamente no balcão para conciliar com a comanda correta.',
    amount: 45,
    timeLabel: 'há 3 min',
    status: 'new',
    archived: false,
    linked: false,
    hasPreInvoice: false,
    tags: ['Captura manual', 'Foto'],
  },
  {
    id: 'mock-capture-02',
    kind: 'capture',
    title: '1x X-Tudo',
    description: 'Anotação rápida de item vendido. Organizar com a comanda depois.',
    timeLabel: 'há 17 min',
    status: 'new',
    archived: false,
    linked: false,
    hasPreInvoice: false,
    tags: ['Texto livre'],
  },
  {
    id: 'mock-payment-01',
    kind: 'payment',
    title: 'Comprovante Pix — R$ 45,00',
    description: 'Recebimento local aguardando vínculo manual com a comanda correspondente.',
    amount: 45,
    timeLabel: 'hoje, 10:42',
    status: 'pending',
    archived: false,
    linked: false,
    hasPreInvoice: false,
    tags: ['PIX', 'Sem vínculo'],
  },
  {
    id: 'mock-sale-01',
    kind: 'sale',
    title: 'Comanda Mesa 1',
    description: '1x X-Tudo, 1x Coca-Cola. Aguardando associação manual com o pagamento.',
    amount: 45,
    timeLabel: 'hoje, 10:38',
    status: 'pending',
    archived: false,
    linked: false,
    hasPreInvoice: false,
    tags: ['Venda manual', 'Sem pagamento'],
  },
  {
    id: 'mock-expense-01',
    kind: 'expense',
    title: 'Despesa fornecedor — R$ 120,00',
    description: 'Compra de insumos registrada localmente; falta definir a categoria contábil.',
    amount: 120,
    timeLabel: 'ontem, 16:20',
    status: 'review',
    archived: false,
    linked: false,
    hasPreInvoice: false,
    tags: ['Despesa', 'Categoria pendente'],
  },
  {
    id: 'mock-stock-01',
    kind: 'stock',
    title: 'Café Torrado Exemplo — 12 un.',
    description: 'Entrada fictícia conferida e pronta para organização do estoque.',
    amount: 238.8,
    timeLabel: 'ontem, 14:05',
    status: 'ready',
    archived: false,
    linked: false,
    hasPreInvoice: false,
    tags: ['Produto', 'Estoque'],
  },
  {
    id: 'mock-invoice-draft-01',
    kind: 'invoice-draft',
    title: 'Rascunho de nota #EX-018',
    description: 'Resumo visual fictício para conferência. Não é documento fiscal, não tem valor fiscal e não será emitido.',
    amount: 320,
    timeLabel: 'ontem, 11:10',
    status: 'review',
    archived: false,
    linked: true,
    hasPreInvoice: false,
    tags: ['Rascunho', 'Sem valor fiscal'],
  },
  {
    id: 'mock-pre-invoice-01',
    kind: 'pre-invoice',
    title: 'Pré-nota visual #EX-007',
    description: 'Resumo visual fictício para conferência manual. Não é nota fiscal e nenhuma emissão foi realizada.',
    amount: 540,
    timeLabel: 'segunda, 15:30',
    status: 'ready',
    archived: false,
    linked: true,
    hasPreInvoice: true,
    tags: ['Pré-nota', 'Conferida'],
  },
  {
    id: 'mock-package-01',
    kind: 'accountant-package',
    title: 'Pacote do contador — Maio (exemplo)',
    description: 'Agrupamento visual fictício de 8 registros, sem envio externo.',
    timeLabel: 'segunda, 09:00',
    status: 'ready',
    archived: false,
    linked: true,
    hasPreInvoice: false,
    tags: ['Contador', 'Não enviado'],
  },
  {
    id: 'mock-archived-01',
    kind: 'expense',
    title: 'Recibo descartado — exemplo',
    description: 'Registro fictício arquivado manualmente e disponível para restauração.',
    amount: 19.9,
    timeLabel: 'sexta, 17:45',
    status: 'review',
    archived: true,
    linked: false,
    hasPreInvoice: false,
    tags: ['Arquivado'],
  },
];
