export class FiscalDedicatedClosureCriteria {
  public static getCriteria() {
    return [
      { id: 'C-DC-01', description: 'Blueprint 11.1 criado.', met: true },
      { id: 'C-DC-02', description: 'Provisioning dry-run 11.2 criado.', met: true },
      { id: 'C-DC-03', description: 'Simulation harness 11.3 criado.', met: true },
      { id: 'C-DC-04', description: 'Replay harness 11.4 criado.', met: true },
      { id: 'C-DC-05', description: 'Ambiente dedicado real continua desativado.', met: true },
      { id: 'C-DC-06', description: 'Infraestrutura real continua não provisionada.', met: true },
      { id: 'C-DC-07', description: 'Banco real continua não criado.', met: true },
      { id: 'C-DC-08', description: 'Banco real continua não conectado.', met: true },
      { id: 'C-DC-09', description: 'Vault real continua não criado.', met: true },
      { id: 'C-DC-10', description: 'Secret real continua não carregado.', met: true },
      { id: 'C-DC-11', description: 'Certificado real continua não carregado.', met: true },
      { id: 'C-DC-12', description: 'PFX real continua não lido.', met: true },
      { id: 'C-DC-13', description: 'Senha de certificado continua não lida.', met: true },
      { id: 'C-DC-14', description: 'SEFAZ real continua desativada.', met: true },
      { id: 'C-DC-15', description: 'XML real continua não assinado.', met: true },
      { id: 'C-DC-16', description: 'PDF real continua não gerado.', met: true },
      { id: 'C-DC-17', description: 'Release real continua desativado.', met: true },
      { id: 'C-DC-18', description: 'Canary real continua desativado.', met: true },
      { id: 'C-DC-19', description: 'Produção V2 continua desativada.', met: true },
      { id: 'C-DC-20', description: 'Tráfego real não foi capturado.', met: true },
      { id: 'C-DC-21', description: 'Tráfego real não foi processado.', met: true },
      { id: 'C-DC-22', description: 'Endpoint real não foi chamado.', met: true },
      { id: 'C-DC-23', description: 'Handler legado não foi chamado.', met: true },
      { id: 'C-DC-24', description: 'Handler V2 operacional não foi chamado.', met: true },
      { id: 'C-DC-25', description: 'app.use legado não foi alterado.', met: true },
      { id: 'C-DC-26', description: 'Middleware real não foi instalado.', met: true },
      { id: 'C-DC-27', description: 'Tap real não foi instalado.', met: true },
      { id: 'C-DC-28', description: 'Worker automático não foi criado.', met: true },
      { id: 'C-DC-29', description: 'Scheduler não foi criado.', met: true },
      { id: 'C-DC-30', description: 'Cron/setInterval/queue.process não foi criado.', met: true },
      { id: 'C-DC-31', description: 'Escrita em tabela fiscal real não ocorreu.', met: true },
      { id: 'C-DC-32', description: 'Payload bruto não foi exposto.', met: true },
      { id: 'C-DC-33', description: 'Dado sensível não foi exposto.', met: true },
      { id: 'C-DC-34', description: 'Boot Policy permanece preservada.', met: true },
      { id: 'C-DC-35', description: 'RLS permanece preservado.', met: true },
      { id: 'C-DC-36', description: 'Rotas legadas permanecem preservadas.', met: true },
      { id: 'C-DC-37', description: 'Respostas legadas permanecem preservadas.', met: true },
      { id: 'C-DC-38', description: 'Scripts temporários foram removidos ou justificados.', met: true },
      { id: 'C-DC-39', description: 'Fechamento documental pode ser aprovado com ressalvas.', met: true },
      { id: 'C-DC-40', description: 'Ativação real permanece bloqueada.', met: true }
    ];
  }
}
