import {
  FiscalProductionPostGoLiveStabilizationInput,
  FiscalProductionPostGoLiveStabilizationResult,
  FiscalProductionPostGoLiveStabilizationStatus
} from './FiscalProductionPostGoLiveStabilizationTypes';
import { FiscalProductionPostGoLiveStabilizationValidator } from './FiscalProductionPostGoLiveStabilizationValidator';
import { FiscalProductionPostGoLiveStabilizationEvaluationService } from './FiscalProductionPostGoLiveStabilizationEvaluationService';

export class FiscalProductionPostGoLiveStabilizationDecisionService {
  public static simulateDecision(input: FiscalProductionPostGoLiveStabilizationInput): FiscalProductionPostGoLiveStabilizationResult {
    const errors = FiscalProductionPostGoLiveStabilizationValidator.validate(input);
    const warnings = FiscalProductionPostGoLiveStabilizationEvaluationService.evaluate(input);

    const isBlocked = errors.length > 0;

    return {
      success: !isBlocked,
      status: isBlocked ? FiscalProductionPostGoLiveStabilizationStatus.BLOCKED_FOR_REAL_POST_GO_LIVE_OBSERVATION_OR_ACTIVATION : FiscalProductionPostGoLiveStabilizationStatus.PRODUCTION_POST_GO_LIVE_STABILIZATION_BLUEPRINT_READY,
      validationExecuted: true,
      evaluationExecuted: true,
      decisionSimulated: true,
      stabilizationBlueprintGenerated: true,
      noActivationObservationContractGenerated: true,
      stabilizationWindowSimulationPlanGenerated: true,
      operationalHealthNoCaptureMatrixGenerated: true,
      legacyContinuityPostGoLivePlanGenerated: true,
      v2InactiveObservationMatrixGenerated: true,
      trafficInvariantPostGoLiveMatrixGenerated: true,
      rollbackReadinessNoExecutePlanGenerated: true,
      incidentReadinessNoOpenPlanGenerated: true,
      noRealObservationEvidenceGenerated: true,
      noActivationPostGoLiveEvidenceGenerated: true,
      dependencyMatrixGenerated: true,
      blockersGenerated: true,
      risksGenerated: true,
      go: false,
      noGo: true,
      blockers: errors,
      warnings,
      productionPostGoLiveStabilizationBlueprintOnly: true,
      noActivationObservationContractOnly: true,
      stabilizationWindowSimulationOnly: true,
      realProductionObserved: false,
      realMetricsCaptured: false,
      realObservabilityInstalled: false,
      realDashboardCreated: false,
      realAlertCreated: false,
      realIncidentOpened: false,
      realRunbookExecuted: false,
      realRemediationExecuted: false,
      realGoLiveConcluded: false,
      realCutoverExecuted: false,
      productionV2Activated: false,
      routeToV2: false,
      routeToLegacy: true,
      trafficChanged: false,
      realLoadBalancerSwitched: false,
      realDnsChanged: false,
      realProxyInstalled: false,
      realMiddlewareInstalled: false,
      realTapInstalled: false,
      realShadowTrafficEnabled: false,
      realRequestCaptured: false,
      realResponseCaptured: false,
      realPayloadCaptured: false,
      realLegacyHandlerCalled: false,
      realV2HandlerCalled: false,
      realExecutionGateUnlocked: false,
      realAuthorizationGranted: false,
      realAuthorizationTokenIssued: false,
      realRollbackExecuted: false,
      realAbortExecuted: false,
      realFallbackExecuted: false,
      realReleaseExecuted: false,
      realRolloutExecuted: false,
      realCanaryActivated: false,
      realShutdownExecuted: false,
      realRuntimeStarted: false,
      realQueueStarted: false,
      realJobEnqueued: false,
      realWorkerDispatched: false,
      realShellCommandExecuted: false,
      realDatabaseConnected: false,
      dmlExecuted: false,
      ddlExecuted: false,
      realSefazCalled: false,
      realPayloadRead: false,
      realXmlRead: false,
      realPdfRead: false,
      realPfxRead: false,
      realCertificateRead: false,
      certificatePasswordRead: false,
      realSecretRead: false,
      privateKeyRead: false,
      tokenRead: false,
      realCryptoUsed: false,
      realHashCalculated: false,
      xmlSigned: false,
      pdfGenerated: false,
      fileSystemWritten: false,
      externalStorageUploaded: false,
      realTicketCreated: false,
      webhookSent: false,
      slackSent: false,
      whatsappSent: false,
      emailSent: false,
      pagerSent: false,
      pagerDutySent: false,
      opsgenieSent: false,
      realStakeholderNotified: false,
      realApproverNotified: false,
      realCustomerNotified: false,
      realOperatorNotified: false,
      readOnly: true,
      governanceOnly: true,
      simulationOnly: true,
      activationBlocked: true,
      payloadIncluded: false,
      sensitiveDataIncluded: false,
      approvedForStabilizationDocumentation: true,
      approvedForNoActivationObservation: true,
      approvedForLegacyContinuityReview: true,
      approvedForRealPostGoLiveObservation: false,
      approvedForProductionV2: false,
      approvedForRouteToV2: false
    };
  }
}
