import {
  FiscalProductionQueueWorkerInput,
  FiscalProductionQueueWorkerResult,
  FiscalProductionQueueWorkerStatus
} from './FiscalProductionQueueWorkerTypes';
import { FiscalProductionQueueWorkerValidator } from './FiscalProductionQueueWorkerValidator';
import { FiscalProductionQueueWorkerEvaluationService } from './FiscalProductionQueueWorkerEvaluationService';

export class FiscalProductionQueueWorkerDecisionService {
  public static simulateDecision(input: FiscalProductionQueueWorkerInput): FiscalProductionQueueWorkerResult {
    const errors = FiscalProductionQueueWorkerValidator.validate(input);
    const warnings = FiscalProductionQueueWorkerEvaluationService.evaluate(input);
    
    const isBlocked = errors.length > 0;

    return {
      success: !isBlocked,
      status: isBlocked ? FiscalProductionQueueWorkerStatus.BLOCKED_FOR_REAL_QUEUE_WORKER_EXECUTION : FiscalProductionQueueWorkerStatus.PRODUCTION_QUEUE_WORKER_DRY_RUN_READY,
      validationExecuted: true,
      evaluationExecuted: true,
      decisionSimulated: true,
      queueTopologyNoStartBlueprintGenerated: true,
      workerDispatchNoOpPlanGenerated: true,
      jobEnqueueNoOpMatrixGenerated: true,
      batchMicroBatchNoExecutePlanGenerated: true,
      retryBackoffNoActivationMatrixGenerated: true,
      deadLetterQueueNoCreatePlanGenerated: true,
      consumerProducerNoStartMatrixGenerated: true,
      concurrencyPoolNoOpenPlanGenerated: true,
      jobPayloadNoReadPlanGenerated: true,
      queueWorkerNoRealDispatchEvidenceGenerated: true,
      queueWorkerNoRealProcessingEvidenceGenerated: true,
      dependencyMatrixGenerated: true,
      blockersGenerated: true,
      risksGenerated: true,
      go: false,
      noGo: true,
      blockers: errors,
      warnings,
      productionQueueWorkerTopologyDryRunOnly: true,
      queueNoStartOnly: true,
      workerNoDispatchOnly: true,
      jobNoEnqueueOnly: true,
      batchMicroBatchNoExecuteOnly: true,
      retryDlqNoActivationOnly: true,
      realQueueStarted: false,
      realJobEnqueued: false,
      realWorkerDispatched: false,
      realDispatcherCreated: false,
      realBatchExecuted: false,
      realMicroBatchExecuted: false,
      realRetryActivated: false,
      realDeadLetterQueueCreated: false,
      realConsumerStarted: false,
      realProducerStarted: false,
      realConcurrencyPoolOpened: false,
      realPayloadProcessed: false,
      realRuntimeStarted: false,
      realSchedulerCreated: false,
      realCronCreated: false,
      realShellCommandExecuted: false,
      realCommandRunnerExecuted: false,
      realProcessManagerCreated: false,
      realLifecycleRunnerCreated: false,
      realTransactionOpened: false,
      realTransactionCommitted: false,
      realTransactionRolledBack: false,
      realDatabaseConnected: false,
      dmlExecuted: false,
      ddlExecuted: false,
      realSefazCalled: false,
      realPayloadRead: false,
      realXmlRead: false,
      realPdfRead: false,
      realPfxRead: false,
      realCertificateRead: false,
      certificatePasswordRead: false,
      realSecretRead: false,
      privateKeyRead: false,
      tokenRead: false,
      realCryptoUsed: false,
      realHashCalculated: false,
      xmlSigned: false,
      pdfGenerated: false,
      fileSystemWritten: false,
      externalStorageUploaded: false,
      realWebhookSent: false,
      realSlackSent: false,
      realWhatsappSent: false,
      realEmailSent: false,
      realPagerSent: false,
      realExecutionGateUnlocked: false,
      realAuthorizationGranted: false,
      realAuthorizationTokenIssued: false,
      productionV2Activated: false,
      routeToV2: false,
      routeToLegacy: true,
      realTrafficChanged: false,
      realLoadBalancerSwitched: false,
      realDnsChanged: false,
      realProxyInstalled: false,
      realMiddlewareInstalled: false,
      realTapInstalled: false,
      realMirrorEnabled: false,
      realSnifferEnabled: false,
      realShadowTrafficEnabled: false,
      realRequestCaptured: false,
      realResponseCaptured: false,
      realPayloadCaptured: false,
      readOnly: true,
      governanceOnly: true,
      simulationOnly: true,
      activationBlocked: true,
      payloadIncluded: false,
      sensitiveDataIncluded: false,
      approvedForQueueTopologyDocumentation: true,
      approvedForWorkerDispatchModeling: true,
      approvedForRealQueueStart: false,
      approvedForRealJobEnqueue: false,
      approvedForRealWorkerDispatch: false,
      approvedForProductionV2: false,
      approvedForRouteToV2: false
    };
  }
}
