import {
  FiscalProductionGoLiveRollbackInput,
  FiscalProductionGoLiveRollbackResult,
  FiscalProductionGoLiveRollbackStatus
} from './FiscalProductionGoLiveRollbackTypes';
import { FiscalProductionGoLiveRollbackValidator } from './FiscalProductionGoLiveRollbackValidator';
import { FiscalProductionGoLiveRollbackEvaluationService } from './FiscalProductionGoLiveRollbackEvaluationService';

export class FiscalProductionGoLiveRollbackDecisionService {
  public static simulateDecision(input: FiscalProductionGoLiveRollbackInput): FiscalProductionGoLiveRollbackResult {
    const errors = FiscalProductionGoLiveRollbackValidator.validate(input);
    const warnings = FiscalProductionGoLiveRollbackEvaluationService.evaluate(input);

    const isBlocked = errors.length > 0;

    return {
      success: !isBlocked,
      status: isBlocked ? FiscalProductionGoLiveRollbackStatus.BLOCKED_FOR_REAL_ROLLBACK_ABORT_OR_FALLBACK : FiscalProductionGoLiveRollbackStatus.PRODUCTION_GO_LIVE_ROLLBACK_NO_OP_READY,
      validationExecuted: true,
      evaluationExecuted: true,
      decisionSimulated: true,
      rollbackNoOpBlueprintGenerated: true,
      cutoverAbortNoOpPlanGenerated: true,
      legacyFallbackSafetyPlanGenerated: true,
      rollbackEligibilitySimulationMatrixGenerated: true,
      trafficReversionNoOpMatrixGenerated: true,
      v2ShutdownNoOpMatrixGenerated: true,
      rollbackTriggerNoExecuteMatrixGenerated: true,
      postAbortContinuityMatrixGenerated: true,
      noRealRollbackEvidenceGenerated: true,
      noRealFallbackEvidenceGenerated: true,
      dependencyMatrixGenerated: true,
      blockersGenerated: true,
      risksGenerated: true,
      go: false,
      noGo: true,
      blockers: errors,
      warnings,
      productionGoLiveRollbackNoOpOnly: true,
      cutoverAbortNoOpOnly: true,
      legacyFallbackSafetyOnly: true,
      realRollbackExecuted: false,
      realAbortExecuted: false,
      realFallbackExecuted: false,
      realTrafficReverted: false,
      realKillSwitchActivated: false,
      realShutdownExecuted: false,
      productionV2Activated: false,
      routeToV2: false,
      routeToLegacy: true,
      trafficChanged: false,
      realLoadBalancerSwitched: false,
      realDnsChanged: false,
      realProxyInstalled: false,
      realMiddlewareInstalled: false,
      realTapInstalled: false,
      realShadowTrafficEnabled: false,
      realRequestCaptured: false,
      realResponseCaptured: false,
      realPayloadCaptured: false,
      realLegacyHandlerCalled: false,
      realV2HandlerCalled: false,
      realExecutionGateUnlocked: false,
      realAuthorizationGranted: false,
      realAuthorizationTokenIssued: false,
      realDeployExecuted: false,
      realReleaseExecuted: false,
      realRolloutExecuted: false,
      realCanaryActivated: false,
      realRuntimeStarted: false,
      realQueueStarted: false,
      realJobEnqueued: false,
      realWorkerDispatched: false,
      realShellCommandExecuted: false,
      realDatabaseConnected: false,
      dmlExecuted: false,
      ddlExecuted: false,
      realSefazCalled: false,
      realPayloadRead: false,
      realXmlRead: false,
      realPdfRead: false,
      realPfxRead: false,
      realCertificateRead: false,
      certificatePasswordRead: false,
      realSecretRead: false,
      privateKeyRead: false,
      tokenRead: false,
      realCryptoUsed: false,
      realHashCalculated: false,
      xmlSigned: false,
      pdfGenerated: false,
      fileSystemWritten: false,
      externalStorageUploaded: false,
      realIncidentCreated: false,
      realTicketCreated: false,
      realRemediationExecuted: false,
      webhookSent: false,
      slackSent: false,
      whatsappSent: false,
      emailSent: false,
      pagerSent: false,
      pagerDutySent: false,
      opsgenieSent: false,
      realStakeholderNotified: false,
      realApproverNotified: false,
      realCustomerNotified: false,
      realOperatorNotified: false,
      readOnly: true,
      governanceOnly: true,
      simulationOnly: true,
      activationBlocked: true,
      payloadIncluded: false,
      sensitiveDataIncluded: false,
      approvedForRollbackNoOp: true,
      approvedForCutoverAbortNoOp: true,
      approvedForLegacyFallbackSafety: true,
      approvedForRealRollback: false,
      approvedForRealAbort: false,
      approvedForRealFallback: false,
      approvedForRealTrafficReversion: false,
      approvedForProductionV2: false,
      approvedForRouteToV2: false
    };
  }
}
